import React, { useEffect, useMemo, useState } from 'react'
import { CheckCircle2, ClipboardCheck, Save } from 'lucide-react'
import { useAuth } from '../contexts/AuthContext'
import { getSchoolClassMembers, getSchoolRegister, listSchoolClasses, listSchoolPupils, saveSchoolRegister, SCHOOL_ATTENDANCE_MARKS } from '../lib/schoolService'

function today() { return new Date().toISOString().slice(0,10) }

export default function SchoolRegistersPage() {
  const { session } = useAuth(); const [date,setDate]=useState(today()); const [sessionType,setSessionType]=useState('AM'); const [formGroup,setFormGroup]=useState(''); const [classId,setClassId]=useState(''); const [periodLabel,setPeriodLabel]=useState(''); const [allPupils,setAllPupils]=useState([]); const [classes,setClasses]=useState([]); const [pupils,setPupils]=useState([]); const [marks,setMarks]=useState({}); const [register,setRegister]=useState(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState('')
  useEffect(()=>{ Promise.all([listSchoolPupils(''),listSchoolClasses()]).then(([p,c])=>{setAllPupils(p);setClasses(c)}).catch(e=>setError(e?.message||'Unable to load register data.')) },[])
  const formGroups=useMemo(()=>[...new Set(allPupils.map((p)=>String(p.form_group||'').trim()).filter(Boolean))].sort(),[allPupils])
  async function loadRegister(){ setBusy(true);setError('');setNotice(''); try { let roster=[]; if(sessionType==='LESSON'){ if(!classId){setPupils([]);setRegister(null);return} roster=await getSchoolClassMembers(classId) } else roster=allPupils.filter((p)=>!formGroup||String(p.form_group||'')===formGroup); const existing=await getSchoolRegister({date,sessionType,classId:sessionType==='LESSON'?classId:null,formGroup:sessionType==='LESSON'?'':formGroup,periodLabel:sessionType==='LESSON'?periodLabel:''}); const next={}; roster.forEach((p)=>{next[p.id]={mark_code:'N',minutes_late:0,note:''}}); (existing?.marks||[]).forEach((m)=>{next[m.pupil_id]={mark_code:m.mark_code||'N',minutes_late:m.minutes_late||0,note:m.note||''}}); setPupils(roster);setMarks(next);setRegister(existing) } catch(e){setError(e?.message||'Unable to open register.')} finally{setBusy(false)} }
  useEffect(()=>{ if(allPupils.length||classes.length) void loadRegister() },[date,sessionType,formGroup,classId,periodLabel,allPupils.length,classes.length])
  function markAll(code){ const next={}; pupils.forEach((p)=>{next[p.id]={...(marks[p.id]||{}),mark_code:code}}); setMarks(next) }
  async function save(completed=false){ if(!pupils.length){setError('There are no pupils in this register.');return} setBusy(true);setError('');setNotice(''); try { await saveSchoolRegister({date,sessionType,classId:sessionType==='LESSON'?classId:null,formGroup:sessionType==='LESSON'?'':formGroup,periodLabel:sessionType==='LESSON'?periodLabel:'',marks:pupils.map((p)=>({pupil_id:p.id,...marks[p.id]})),completed,takenByName:session?.profile?.display_name||''}); setNotice(completed?'Register completed.':'Register saved.'); await loadRegister() } catch(e){setError(e?.message||'Unable to save register.')} finally{setBusy(false)} }
  const counts=useMemo(()=>pupils.reduce((acc,p)=>{const c=marks[p.id]?.mark_code||'N';acc[c]=(acc[c]||0)+1;return acc},{}),[pupils,marks])
  return <div className="school-page page-pad compact-pad"><div className="school-page-head"><div><span>RO-SCHOOL · REGISTERS</span><h1>Take register</h1></div><div className="school-register-status"><ClipboardCheck size={18}/><span>{register?.status==='completed'?'Completed':'Open / unsaved'}</span></div></div>
    <section className="school-register-controls"><label>Date<input type="date" value={date} onChange={(e)=>setDate(e.target.value)}/></label><label>Session<select value={sessionType} onChange={(e)=>{setSessionType(e.target.value);setClassId('');setFormGroup('')}}><option value="AM">AM registration</option><option value="PM">PM registration</option><option value="LESSON">Lesson register</option></select></label>{sessionType==='LESSON'?<><label>Class<select value={classId} onChange={(e)=>setClassId(e.target.value)}><option value="">Choose class…</option>{classes.map(c=><option key={c.id} value={c.id}>{c.code} · {c.name}</option>)}</select></label><label>Period<input value={periodLabel} onChange={(e)=>setPeriodLabel(e.target.value)} placeholder="Period 3"/></label></>:<label>Form group<select value={formGroup} onChange={(e)=>setFormGroup(e.target.value)}><option value="">All pupils</option>{formGroups.map(g=><option key={g}>{g}</option>)}</select></label>}<button onClick={loadRegister} disabled={busy}>Refresh</button></section>
    {error&&<div className="form-error">{error}</div>}{notice&&<div className="form-success">{notice}</div>}
    <div className="school-register-toolbar"><div><button onClick={()=>markAll('P')}>Mark all present</button><button onClick={()=>markAll('N')}>Clear to N</button></div><div>{Object.entries(counts).sort().map(([code,count])=><span key={code}><b>{code}</b>{count}</span>)}</div></div>
    <div className="school-register-table-wrap"><table className="school-register-table"><thead><tr><th>Pupil</th><th>Year / Form</th><th>Mark</th><th>Late (mins)</th><th>Note</th></tr></thead><tbody>{pupils.map(p=><tr key={p.id}><td><strong>{p.last_name}, {p.preferred_name||p.first_name}</strong><small>{p.admission_number}</small></td><td>{p.year_group||'—'} / {p.form_group||'—'}</td><td><select className={`mark-code mark-${marks[p.id]?.mark_code||'N'}`} value={marks[p.id]?.mark_code||'N'} onChange={(e)=>setMarks({...marks,[p.id]:{...(marks[p.id]||{}),mark_code:e.target.value}})}>{SCHOOL_ATTENDANCE_MARKS.map(m=><option key={m.code} value={m.code}>{m.code} — {m.label}</option>)}</select></td><td><input type="number" min="0" max="240" value={marks[p.id]?.minutes_late||0} disabled={(marks[p.id]?.mark_code||'N')!=='L'} onChange={(e)=>setMarks({...marks,[p.id]:{...(marks[p.id]||{}),minutes_late:e.target.value}})}/></td><td><input value={marks[p.id]?.note||''} onChange={(e)=>setMarks({...marks,[p.id]:{...(marks[p.id]||{}),note:e.target.value}})} placeholder="Optional note"/></td></tr>)}</tbody></table>{!pupils.length&&<div className="empty-state">Choose a class/form group with pupils to take a register.</div>}</div>
    <div className="school-register-actions"><button onClick={()=>save(false)} disabled={busy||!pupils.length}><Save size={14}/>Save draft</button><button className="primary-button" onClick={()=>save(true)} disabled={busy||!pupils.length}><CheckCircle2 size={14}/>{busy?'Saving…':'Complete register'}</button></div>
  </div>
}
