import React, { useEffect, useMemo, useState } from 'react'
import { Plus, Save, UsersRound } from 'lucide-react'
import { createSchoolClass, getSchoolClassMembers, listSchoolClasses, listSchoolPupils, setSchoolClassMembers } from '../lib/schoolService'

const EMPTY = { code: '', name: '', subject: '', year_group: '', room: '', teacher_name: '', class_type: 'lesson' }

export default function SchoolClassesPage() {
  const [classes, setClasses] = useState([]); const [pupils, setPupils] = useState([]); const [selected, setSelected] = useState(null); const [memberIds, setMemberIds] = useState([]); const [form, setForm] = useState(EMPTY); const [showForm, setShowForm] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  async function load() { setError(''); try { const [c,p] = await Promise.all([listSchoolClasses(), listSchoolPupils('')]); setClasses(c); setPupils(p) } catch(e) { setError(e?.message || 'Unable to load classes.') } }
  useEffect(() => { void load() }, [])
  async function choose(row) { setSelected(row); setNotice(''); try { setMemberIds((await getSchoolClassMembers(row.id)).map((p) => String(p.id))) } catch(e) { setError(e?.message || 'Unable to load class membership.') } }
  async function create(event) { event.preventDefault(); setBusy(true); setError(''); try { await createSchoolClass({ ...form, code: form.code.trim().toUpperCase(), name: form.name.trim(), subject: form.subject.trim() || null, year_group: form.year_group.trim() || null, room: form.room.trim() || null, teacher_name: form.teacher_name.trim() || null }); setForm(EMPTY); setShowForm(false); await load() } catch(e) { setError(e?.message || 'Unable to create class.') } finally { setBusy(false) } }
  async function saveMembers() { if(!selected) return; setBusy(true); setError(''); setNotice(''); try { await setSchoolClassMembers(selected.id, memberIds); setNotice(`Saved ${memberIds.length} pupils in ${selected.code}.`) } catch(e) { setError(e?.message || 'Unable to save class membership.') } finally { setBusy(false) } }
  const grouped = useMemo(() => [...pupils].sort((a,b) => `${a.year_group}${a.last_name}`.localeCompare(`${b.year_group}${b.last_name}`)), [pupils])
  return <div className="school-page page-pad compact-pad"><div className="school-page-head"><div><span>RO-SCHOOL · CLASSES</span><h1>Classes &amp; teaching groups</h1></div><button className="primary-button" onClick={() => setShowForm((v) => !v)}><Plus size={15}/>New class</button></div>
    {error && <div className="form-error">{error}</div>}{notice && <div className="form-success">{notice}</div>}
    {showForm && <form className="school-form" onSubmit={create}><h3>Create class</h3><div className="school-form-grid"><label><span>Class code</span><input required value={form.code} onChange={(e) => setForm({...form,code:e.target.value})} placeholder="10A-MATH"/></label><label><span>Class name</span><input required value={form.name} onChange={(e) => setForm({...form,name:e.target.value})} placeholder="Year 10 Mathematics"/></label><label><span>Type</span><select value={form.class_type} onChange={(e) => setForm({...form,class_type:e.target.value})}><option value="lesson">Lesson class</option><option value="form">Form / tutor group</option><option value="club">Club / activity</option></select></label><label><span>Subject</span><input value={form.subject} onChange={(e) => setForm({...form,subject:e.target.value})}/></label><label><span>Year group</span><input value={form.year_group} onChange={(e) => setForm({...form,year_group:e.target.value})}/></label><label><span>Room</span><input value={form.room} onChange={(e) => setForm({...form,room:e.target.value})}/></label><label className="wide"><span>Teacher / tutor</span><input value={form.teacher_name} onChange={(e) => setForm({...form,teacher_name:e.target.value})}/></label></div><div className="school-form-actions"><button type="button" onClick={() => setShowForm(false)}>Cancel</button><button className="primary-button" disabled={busy}>Create class</button></div></form>}
    <div className="school-split"><section className="school-class-list">{classes.length ? classes.map((row) => <button key={row.id} className={selected?.id === row.id ? 'active' : ''} onClick={() => choose(row)}><UsersRound size={17}/><div><strong>{row.code}</strong><span>{row.name}</span><small>{[row.subject,row.year_group,row.room,row.teacher_name].filter(Boolean).join(' · ') || 'No details'}</small></div></button>) : <div className="empty-state">No classes have been created.</div>}</section>
    <section className="school-members-panel">{selected ? <><header><div><span>CLASS MEMBERS</span><h2>{selected.code} · {selected.name}</h2></div><button className="primary-button" onClick={saveMembers} disabled={busy}><Save size={14}/>Save members</button></header><div className="school-member-list">{grouped.map((pupil) => <label key={pupil.id}><input type="checkbox" checked={memberIds.includes(String(pupil.id))} onChange={(e) => setMemberIds((current) => e.target.checked ? [...new Set([...current,String(pupil.id)])] : current.filter((id) => id !== String(pupil.id)))}/><span><strong>{pupil.last_name}, {pupil.first_name}</strong><small>{pupil.year_group || '—'} · {pupil.form_group || 'No form'} · {pupil.admission_number}</small></span></label>)}</div></> : <div className="empty-state">Select a class to manage its pupils.</div>}</section></div>
  </div>
}
