-- RecordsWeb 3.2.3
-- Per-community Roblox bridge for waiting-room / patient-call displays.
-- Run after the RecordsWeb multi-organisation migrations.

create extension if not exists pgcrypto;

create table if not exists public.recordsweb_roblox_integrations (
  organisation_id uuid primary key references public.organisations(id) on delete cascade,
  enabled boolean not null default false,
  key_hash text unique,
  key_last_four text,
  key_created_at timestamptz,
  universe_id text,
  place_ids text[] not null default '{}'::text[],
  display_name_mode text not null default 'first_name_last_initial'
    check (display_name_mode in ('first_name_last_initial','full_name','record_number')),
  display_duration_seconds integer not null default 12
    check (display_duration_seconds between 5 and 60),
  last_heartbeat_at timestamptz,
  last_universe_id text,
  last_place_id text,
  last_server_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.recordsweb_roblox_display_events (
  id bigint generated by default as identity primary key,
  organisation_id uuid not null references public.organisations(id) on delete cascade,
  appointment_id uuid references public.appointments(id) on delete cascade,
  event_type text not null default 'patient_called' check (event_type in ('patient_called')),
  display_name text not null,
  destination text not null,
  clinician text,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '2 minutes')
);

-- Create a disabled integration settings row for every existing community.
-- The secret connection code is intentionally generated later from Management so
-- its plaintext can be shown exactly once to an authorised manager.
insert into public.recordsweb_roblox_integrations (organisation_id)
select id from public.organisations
on conflict (organisation_id) do nothing;

create index if not exists recordsweb_roblox_events_org_id_idx
  on public.recordsweb_roblox_display_events (organisation_id, id);
create index if not exists recordsweb_roblox_events_expiry_idx
  on public.recordsweb_roblox_display_events (expires_at);
create index if not exists recordsweb_roblox_integration_key_idx
  on public.recordsweb_roblox_integrations (key_hash)
  where key_hash is not null;

alter table public.recordsweb_roblox_integrations enable row level security;
alter table public.recordsweb_roblox_display_events enable row level security;

-- These tables are deliberately not exposed directly to browser/app clients.
-- Authenticated Management users operate them through recordsweb-roblox-admin;
-- Roblox servers operate them through recordsweb-game-api using the per-community secret.
revoke all on table public.recordsweb_roblox_integrations from anon, authenticated;
revoke all on table public.recordsweb_roblox_display_events from anon, authenticated;

create or replace function public.recordsweb_queue_roblox_patient_call()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_integration public.recordsweb_roblox_integrations%rowtype;
  v_patient public.patients%rowtype;
  v_display_name text;
  v_destination text;
  v_should_call boolean := false;
begin
  if new.organisation_id is null or new.patient_id is null then
    return new;
  end if;

  if tg_op = 'INSERT' then
    v_should_call := new.status in ('Sent in', 'In consultation');
  else
    v_should_call := new.status in ('Sent in', 'In consultation')
      and old.status is distinct from new.status
      and coalesce(old.status, '') not in ('Sent in', 'In consultation');
  end if;

  if not v_should_call then
    return new;
  end if;

  select * into v_integration
  from public.recordsweb_roblox_integrations
  where organisation_id = new.organisation_id
    and enabled = true
    and key_hash is not null;

  if not found then
    return new;
  end if;

  select * into v_patient
  from public.patients
  where id = new.patient_id
    and organisation_id = new.organisation_id;

  if not found then
    return new;
  end if;

  case v_integration.display_name_mode
    when 'full_name' then
      v_display_name := trim(concat_ws(' ', nullif(v_patient.title, ''), v_patient.first_name, v_patient.last_name));
    when 'record_number' then
      v_display_name := case
        when nullif(trim(coalesce(v_patient.emis_number, '')), '') is not null
          then 'Patient ' || trim(v_patient.emis_number)
        else 'Patient'
      end;
    else
      v_display_name := trim(v_patient.first_name || ' ' || left(v_patient.last_name, 1) || '.');
  end case;

  v_destination := coalesce(nullif(trim(new.room), ''), 'Consulting room');

  insert into public.recordsweb_roblox_display_events (
    organisation_id,
    appointment_id,
    event_type,
    display_name,
    destination,
    clinician,
    expires_at
  ) values (
    new.organisation_id,
    new.id,
    'patient_called',
    v_display_name,
    v_destination,
    nullif(trim(coalesce(new.clinician, '')), ''),
    now() + interval '2 minutes'
  );

  -- Keep the queue table small without deleting events that a temporarily
  -- disconnected server might still need during their short validity window.
  delete from public.recordsweb_roblox_display_events
  where organisation_id = new.organisation_id
    and expires_at < now() - interval '1 day';

  return new;
end;
$$;

revoke all on function public.recordsweb_queue_roblox_patient_call() from public;

-- Separate triggers keep compatibility across PostgreSQL versions while
-- supporting both appointments created already in the sent-in state and later updates.
drop trigger if exists recordsweb_roblox_patient_call_insert on public.appointments;
create trigger recordsweb_roblox_patient_call_insert
after insert on public.appointments
for each row execute function public.recordsweb_queue_roblox_patient_call();

drop trigger if exists recordsweb_roblox_patient_call_update on public.appointments;
create trigger recordsweb_roblox_patient_call_update
after update of status on public.appointments
for each row execute function public.recordsweb_queue_roblox_patient_call();

comment on table public.recordsweb_roblox_integrations is
  'RecordsWeb 3.2.3 per-community Roblox bridge settings and hashed connection credentials.';
comment on table public.recordsweb_roblox_display_events is
  'Short-lived server-to-server patient-call events consumed by authorised Roblox game servers.';
