-- RecordsWeb 3.2.8 — realistic medication workflow + consultation problem creation
-- Run after recordsweb-3.2.7-billing-grace-readonly.sql.
--
-- Adds:
--   * PDF-catalogue metadata on medication records
--   * specialist-drug GP Partner authorisation enforcement
--   * medication issue/history events
--   * cancel-course action with mandatory reason
--   * re-authorisation with prescribing PIN
--   * automatic Problems creation when a consultation records a new problem

begin;

alter table public.medications add column if not exists catalogue_id text;
alter table public.medications add column if not exists form text;
alter table public.medications add column if not exists indication text;
alter table public.medications add column if not exists reference_usual_dose text;
alter table public.medications add column if not exists reference_higher_dose text;
alter table public.medications add column if not exists specialist_only boolean not null default false;
alter table public.medications add column if not exists specialist_authorised_by uuid references public.profiles(id) on delete set null;
alter table public.medications add column if not exists specialist_authorised_at timestamptz;
alter table public.medications add column if not exists prescription_count integer not null default 1;
alter table public.medications add column if not exists cancelled_at timestamptz;
alter table public.medications add column if not exists cancellation_reason text;
alter table public.medications add column if not exists cancelled_by text;
alter table public.medications add column if not exists last_reauthorised_at timestamptz;
alter table public.medications add column if not exists last_reauthorised_by text;

update public.medications
set prescription_count = 1
where prescription_count is null or prescription_count < 1;

alter table public.consultations add column if not exists problem_id uuid references public.problems(id) on delete set null;

create table if not exists public.medication_events (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.patients(id) on delete cascade,
  medication_id uuid references public.medications(id) on delete cascade,
  medication_name text not null,
  event_type text not null,
  reason text,
  clinician_id uuid references public.profiles(id) on delete set null,
  clinician_name text,
  prescribing_pin_used boolean not null default false,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint medication_events_type_allowed check (event_type in ('prescribed','updated','cancelled','reauthorised'))
);

create index if not exists medication_events_patient_name_idx
  on public.medication_events (patient_id, medication_name, created_at desc);
create index if not exists medication_events_medication_idx
  on public.medication_events (medication_id, created_at desc);

alter table public.medication_events enable row level security;

drop policy if exists "medication_events_read" on public.medication_events;
create policy "medication_events_read"
on public.medication_events for select to authenticated
using (
  exists (
    select 1
    from public.patients p
    where p.id = patient_id
      and p.organisation_id = public.current_organisation_id()
  )
);

-- History rows can only be generated by the secured prescribing functions.
revoke insert, update, delete on public.medication_events from authenticated, anon;
grant select on public.medication_events to authenticated;

-- Backfill one initial "prescribed" history entry for legacy medication rows.
insert into public.medication_events (
  patient_id,
  medication_id,
  medication_name,
  event_type,
  clinician_name,
  prescribing_pin_used,
  details,
  created_at
)
select
  m.patient_id,
  m.id,
  m.name,
  'prescribed',
  m.authoriser,
  false,
  jsonb_build_object('legacy_backfill', true),
  coalesce(m.created_at, now())
from public.medications m
where not exists (
  select 1 from public.medication_events e
  where e.medication_id = m.id
    and e.event_type = 'prescribed'
);

-- New table also participates in the 3.2.7 billing read-only guard.
do $$
begin
  if to_regprocedure('public.recordsweb_enforce_billing_write_access()') is not null then
    drop trigger if exists recordsweb_billing_write_guard on public.medication_events;
    create trigger recordsweb_billing_write_guard
      before insert or update or delete on public.medication_events
      for each row execute function public.recordsweb_enforce_billing_write_access();
  end if;
end $$;

-- Replace medication save RPC with catalogue metadata, specialist authorisation,
-- history logging, and an explicit billing write check.
create or replace function public.recordsweb_save_medication(
  p_patient_id uuid,
  p_medication_id uuid,
  p_payload jsonb,
  p_pin text
)
returns public.medications
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_profile public.profiles%rowtype;
  v_pin public.prescribing_pins%rowtype;
  v_med public.medications%rowtype;
  v_authoriser text;
  v_type text;
  v_name text;
  v_specialist boolean;
  v_is_gp_partner boolean;
begin
  if auth.uid() is null then raise exception 'You must be signed in.'; end if;
  if not public.recordsweb_billing_write_allowed() then
    raise exception 'RecordsWeb is in read-only mode because this organisation does not currently have write access.' using errcode = '42501';
  end if;
  if p_pin is null or p_pin !~ '^[0-9]{4}$' then raise exception 'Enter your 4-digit prescribing PIN.'; end if;

  select * into v_profile from public.profiles where id = auth.uid() and active = true;
  if not found then raise exception 'Your RecordsWeb profile is not active.'; end if;

  select * into v_pin from public.prescribing_pins where user_id = auth.uid();
  if not found then raise exception 'Create a prescribing PIN before authorising medication.'; end if;
  if v_pin.pin_hash <> crypt(p_pin, v_pin.pin_hash) then raise exception 'Prescribing PIN is incorrect.'; end if;

  if not exists (
    select 1 from public.patients p
    where p.id = p_patient_id and p.organisation_id = v_profile.organisation_id
  ) then raise exception 'Patient is not available to your organisation.'; end if;

  v_name := trim(coalesce(p_payload->>'name',''));
  if v_name = '' then raise exception 'Medication name is required.'; end if;
  if nullif(trim(coalesce(p_payload->>'catalogue_id','')), '') is null then
    raise exception 'Select the medicine from the RecordsWeb GP medicines reference before prescribing.';
  end if;

  v_type := coalesce(nullif(p_payload->>'type',''), 'Acute Meds');
  if v_type not in ('Acute Meds','Repeat','Long Term Meds') then raise exception 'Medication group is invalid.'; end if;

  v_specialist := coalesce((p_payload->>'specialist_only')::boolean, false);
  v_is_gp_partner := v_profile.role = 'GP Partner' or 'GP Partner' = any(coalesce(v_profile.roles, array[]::text[]));
  if v_specialist and not v_is_gp_partner then
    raise exception 'This drug is only allowed to be prescribed by specialists. Please speak to your GP Partner for authorisation to prescribe this drug.' using errcode = '42501';
  end if;

  v_authoriser := coalesce(
    nullif(trim(concat_ws(' ', v_profile.title, v_profile.first_name, v_profile.last_name)), ''),
    v_profile.display_name,
    v_profile.username
  );

  if p_medication_id is null then
    insert into public.medications (
      patient_id, name, dose, quantity, type, last_issue_date,
      authoriser, issues, method, usage, active,
      catalogue_id, form, indication, reference_usual_dose, reference_higher_dose,
      specialist_only, specialist_authorised_by, specialist_authorised_at,
      prescription_count
    ) values (
      p_patient_id,
      v_name,
      nullif(p_payload->>'dose',''),
      nullif(p_payload->>'quantity',''),
      v_type,
      coalesce(nullif(p_payload->>'last_issue_date','')::date, current_date),
      v_authoriser,
      nullif(p_payload->>'issues',''),
      nullif(p_payload->>'method',''),
      nullif(p_payload->>'usage',''),
      coalesce((p_payload->>'active')::boolean, true),
      nullif(p_payload->>'catalogue_id',''),
      nullif(p_payload->>'form',''),
      nullif(p_payload->>'indication',''),
      nullif(p_payload->>'reference_usual_dose',''),
      nullif(p_payload->>'reference_higher_dose',''),
      v_specialist,
      case when v_specialist then auth.uid() else null end,
      case when v_specialist then now() else null end,
      1
    ) returning * into v_med;

    insert into public.medication_events (
      patient_id, medication_id, medication_name, event_type,
      clinician_id, clinician_name, prescribing_pin_used, details
    ) values (
      p_patient_id, v_med.id, v_med.name, 'prescribed',
      auth.uid(), v_authoriser, true,
      jsonb_build_object(
        'dose', v_med.dose,
        'quantity', v_med.quantity,
        'catalogue_id', v_med.catalogue_id,
        'specialist_only', v_med.specialist_only
      )
    );
  else
    update public.medications m set
      name = v_name,
      dose = nullif(p_payload->>'dose',''),
      quantity = nullif(p_payload->>'quantity',''),
      type = v_type,
      last_issue_date = nullif(p_payload->>'last_issue_date','')::date,
      authoriser = v_authoriser,
      issues = nullif(p_payload->>'issues',''),
      method = nullif(p_payload->>'method',''),
      usage = nullif(p_payload->>'usage',''),
      active = coalesce((p_payload->>'active')::boolean, m.active),
      catalogue_id = nullif(p_payload->>'catalogue_id',''),
      form = nullif(p_payload->>'form',''),
      indication = nullif(p_payload->>'indication',''),
      reference_usual_dose = nullif(p_payload->>'reference_usual_dose',''),
      reference_higher_dose = nullif(p_payload->>'reference_higher_dose',''),
      specialist_only = v_specialist,
      specialist_authorised_by = case when v_specialist then auth.uid() else null end,
      specialist_authorised_at = case when v_specialist then now() else null end,
      updated_at = now()
    where m.id = p_medication_id and m.patient_id = p_patient_id
    returning * into v_med;
    if not found then raise exception 'Medication record was not found.'; end if;

    insert into public.medication_events (
      patient_id, medication_id, medication_name, event_type,
      clinician_id, clinician_name, prescribing_pin_used, details
    ) values (
      p_patient_id, v_med.id, v_med.name, 'updated',
      auth.uid(), v_authoriser, true,
      jsonb_build_object(
        'dose', v_med.dose,
        'quantity', v_med.quantity,
        'catalogue_id', v_med.catalogue_id,
        'specialist_only', v_med.specialist_only
      )
    );
  end if;

  return v_med;
end;
$$;

-- Cancel a course. Cancellation deliberately requires a reason, not the
-- prescribing PIN. The action remains attributable to the signed-in clinician.
create or replace function public.recordsweb_cancel_medication(
  p_patient_id uuid,
  p_medication_id uuid,
  p_reason text
)
returns public.medications
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_profile public.profiles%rowtype;
  v_med public.medications%rowtype;
  v_reason text;
  v_clinician text;
begin
  if auth.uid() is null then raise exception 'You must be signed in.'; end if;
  if not public.recordsweb_billing_write_allowed() then
    raise exception 'RecordsWeb is in read-only mode because this organisation does not currently have write access.' using errcode = '42501';
  end if;

  select * into v_profile from public.profiles where id = auth.uid() and active = true;
  if not found then raise exception 'Your RecordsWeb profile is not active.'; end if;

  if not exists (
    select 1 from public.patients p
    where p.id = p_patient_id and p.organisation_id = v_profile.organisation_id
  ) then raise exception 'Patient is not available to your organisation.'; end if;

  v_reason := trim(coalesce(p_reason, ''));
  if length(v_reason) < 3 then raise exception 'Enter a reason for cancelling this medication course.'; end if;

  v_clinician := coalesce(
    nullif(trim(concat_ws(' ', v_profile.title, v_profile.first_name, v_profile.last_name)), ''),
    v_profile.display_name,
    v_profile.username
  );

  update public.medications m set
    active = false,
    cancelled_at = now(),
    cancellation_reason = v_reason,
    cancelled_by = v_clinician,
    updated_at = now()
  where m.id = p_medication_id and m.patient_id = p_patient_id
  returning * into v_med;
  if not found then raise exception 'Medication record was not found.'; end if;

  insert into public.medication_events (
    patient_id, medication_id, medication_name, event_type,
    reason, clinician_id, clinician_name, prescribing_pin_used,
    details
  ) values (
    p_patient_id, v_med.id, v_med.name, 'cancelled',
    v_reason, auth.uid(), v_clinician, false,
    jsonb_build_object('prescription_count', v_med.prescription_count)
  );

  return v_med;
end;
$$;

-- Re-authorise a medicine. This requires the current clinician's prescribing PIN.
-- Specialist medicines additionally require the signed-in clinician to hold the
-- GP Partner role.
create or replace function public.recordsweb_reauthorise_medication(
  p_patient_id uuid,
  p_medication_id uuid,
  p_pin text
)
returns public.medications
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_profile public.profiles%rowtype;
  v_pin public.prescribing_pins%rowtype;
  v_med public.medications%rowtype;
  v_clinician text;
  v_is_gp_partner boolean;
begin
  if auth.uid() is null then raise exception 'You must be signed in.'; end if;
  if not public.recordsweb_billing_write_allowed() then
    raise exception 'RecordsWeb is in read-only mode because this organisation does not currently have write access.' using errcode = '42501';
  end if;
  if p_pin is null or p_pin !~ '^[0-9]{4}$' then raise exception 'Enter your 4-digit prescribing PIN.'; end if;

  select * into v_profile from public.profiles where id = auth.uid() and active = true;
  if not found then raise exception 'Your RecordsWeb profile is not active.'; end if;

  select * into v_pin from public.prescribing_pins where user_id = auth.uid();
  if not found then raise exception 'Create a prescribing PIN before re-authorising medication.'; end if;
  if v_pin.pin_hash <> crypt(p_pin, v_pin.pin_hash) then raise exception 'Prescribing PIN is incorrect.'; end if;

  if not exists (
    select 1 from public.patients p
    where p.id = p_patient_id and p.organisation_id = v_profile.organisation_id
  ) then raise exception 'Patient is not available to your organisation.'; end if;

  select * into v_med
  from public.medications m
  where m.id = p_medication_id and m.patient_id = p_patient_id;
  if not found then raise exception 'Medication record was not found.'; end if;

  v_is_gp_partner := v_profile.role = 'GP Partner' or 'GP Partner' = any(coalesce(v_profile.roles, array[]::text[]));
  if v_med.specialist_only and not v_is_gp_partner then
    raise exception 'This drug is only allowed to be prescribed by specialists. Please speak to your GP Partner for authorisation to prescribe this drug.' using errcode = '42501';
  end if;

  v_clinician := coalesce(
    nullif(trim(concat_ws(' ', v_profile.title, v_profile.first_name, v_profile.last_name)), ''),
    v_profile.display_name,
    v_profile.username
  );

  update public.medications m set
    active = true,
    last_issue_date = current_date,
    authoriser = v_clinician,
    prescription_count = greatest(coalesce(m.prescription_count, 1), 1) + 1,
    last_reauthorised_at = now(),
    last_reauthorised_by = v_clinician,
    cancelled_at = null,
    cancellation_reason = null,
    cancelled_by = null,
    specialist_authorised_by = case when m.specialist_only then auth.uid() else m.specialist_authorised_by end,
    specialist_authorised_at = case when m.specialist_only then now() else m.specialist_authorised_at end,
    updated_at = now()
  where m.id = p_medication_id and m.patient_id = p_patient_id
  returning * into v_med;

  insert into public.medication_events (
    patient_id, medication_id, medication_name, event_type,
    clinician_id, clinician_name, prescribing_pin_used, details
  ) values (
    p_patient_id, v_med.id, v_med.name, 'reauthorised',
    auth.uid(), v_clinician, true,
    jsonb_build_object(
      'prescription_count', v_med.prescription_count,
      'specialist_only', v_med.specialist_only
    )
  );

  return v_med;
end;
$$;

-- Transactional consultation creation. If the clinician enters a Problem but
-- does not select an existing one, RecordsWeb creates (or reuses) an active
-- Problems record and links the consultation to it.
create or replace function public.recordsweb_create_consultation_with_problem(
  p_patient_id uuid,
  p_payload jsonb,
  p_existing_problem_id uuid default null,
  p_new_problem_name text default null
)
returns public.consultations
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile public.profiles%rowtype;
  v_problem public.problems%rowtype;
  v_consultation public.consultations%rowtype;
  v_problem_name text;
begin
  if auth.uid() is null then raise exception 'You must be signed in.'; end if;
  if not public.recordsweb_billing_write_allowed() then
    raise exception 'RecordsWeb is in read-only mode because this organisation does not currently have write access.' using errcode = '42501';
  end if;

  select * into v_profile from public.profiles where id = auth.uid() and active = true;
  if not found then raise exception 'Your RecordsWeb profile is not active.'; end if;

  if not exists (
    select 1 from public.patients p
    where p.id = p_patient_id and p.organisation_id = v_profile.organisation_id
  ) then raise exception 'Patient is not available to your organisation.'; end if;

  if p_existing_problem_id is not null then
    select * into v_problem
    from public.problems p
    where p.id = p_existing_problem_id
      and p.patient_id = p_patient_id;
    if not found then raise exception 'The selected patient problem could not be found.'; end if;
  else
    v_problem_name := left(trim(coalesce(p_new_problem_name, '')), 240);
    if v_problem_name <> '' then
      select * into v_problem
      from public.problems p
      where p.patient_id = p_patient_id
        and lower(trim(p.name)) = lower(v_problem_name)
        and lower(coalesce(p.status, 'Active')) <> 'inactive'
      order by p.created_at desc
      limit 1;

      if not found then
        insert into public.problems (
          patient_id, name, onset_date, status, significance, notes
        ) values (
          p_patient_id,
          v_problem_name,
          current_date,
          'Active',
          'New',
          'Created automatically from a RecordsWeb consultation.'
        ) returning * into v_problem;
      end if;
    end if;
  end if;

  insert into public.consultations (
    patient_id,
    problem_id,
    date,
    clinician,
    location,
    type,
    status,
    entries
  ) values (
    p_patient_id,
    v_problem.id,
    coalesce(nullif(p_payload->>'date','')::timestamptz, now()),
    coalesce(nullif(p_payload->>'clinician',''), v_profile.display_name, v_profile.username),
    nullif(p_payload->>'location',''),
    nullif(p_payload->>'type',''),
    coalesce(nullif(p_payload->>'status',''), 'Complete'),
    coalesce(p_payload->'entries', '[]'::jsonb)
  ) returning * into v_consultation;

  return v_consultation;
end;
$$;

revoke all on function public.recordsweb_save_medication(uuid, uuid, jsonb, text) from public, anon;
revoke all on function public.recordsweb_cancel_medication(uuid, uuid, text) from public, anon;
revoke all on function public.recordsweb_reauthorise_medication(uuid, uuid, text) from public, anon;
revoke all on function public.recordsweb_create_consultation_with_problem(uuid, jsonb, uuid, text) from public, anon;

grant execute on function public.recordsweb_save_medication(uuid, uuid, jsonb, text) to authenticated;
grant execute on function public.recordsweb_cancel_medication(uuid, uuid, text) to authenticated;
grant execute on function public.recordsweb_reauthorise_medication(uuid, uuid, text) to authenticated;
grant execute on function public.recordsweb_create_consultation_with_problem(uuid, jsonb, uuid, text) to authenticated;

-- Medication writes continue to be RPC-only so the PIN/specialist checks cannot
-- be bypassed with a direct client update.
revoke insert, update on public.medications from authenticated, anon;

commit;
