import React,{useEffect,useMemo,useState} from 'react'
import { Bell, Mail, RefreshCcw, X } from 'lucide-react'
import ModalPortal from './ModalPortal'
import { listStaffNotices } from '../lib/dataService'
import { listScreenMessages } from '../lib/staffMessaging'
import { listMyAccountActivity } from '../lib/auditService'
import { hasRecoveryCode } from '../lib/recoverySecurity'
export default function SystemNotificationCenter({session}){
 const userId=session?.user?.id||session?.profile?.id; const [open,setOpen]=useState(false),[items,setItems]=useState([]),[busy,setBusy]=useState(false)
 async function load(){if(!userId)return;setBusy(true);try{const [notices,messages,activity,recoveryReady]=await Promise.all([listStaffNotices(),listScreenMessages(userId),listMyAccountActivity(6),hasRecoveryCode(userId).catch(()=>true)]);const merged=[...(recoveryReady?[]:[{id:'recovery-setup',kind:'Account security',title:'Set up account recovery',detail:'Create a 6-digit recovery code in Account & Security so the sign-in recovery links can be used.',date:new Date().toISOString()}]),...notices.filter(n=>n.active!==false).map(n=>({id:`n-${n.id}`,kind:'Staff notice',title:n.title||'Staff notice',detail:n.body||n.message||'',date:n.published_at||n.created_at})),...messages.filter(m=>!m.read_at).map(m=>({id:`m-${m.id}`,kind:m.urgent?'Urgent screen message':'Screen message',title:m.subject,detail:`From ${m.sender_name}`,date:m.created_at})),...activity.slice(0,3).map(a=>({id:`a-${a.id}`,kind:'Account security',title:a.description||a.action,detail:a.action,date:a.created_at}))];merged.sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));setItems(merged)}finally{setBusy(false)}}
 useEffect(()=>{load().catch(()=>{})},[userId]); const count=useMemo(()=>items.filter(i=>i.kind.includes('message')).length,[items])
 return <><button className="titlebar-notification-button" onClick={()=>{setOpen(true);load().catch(()=>{})}} title="Notifications"><Bell size={15}/>{count>0&&<span>{count>9?'9+':count}</span>}</button>{open&&<ModalPortal onClose={()=>setOpen(false)} ariaLabel="Notifications"><div className="records-modal system-notification-modal"><header><div><strong>Notifications</strong><span>RecordsWeb notifications centre</span></div><div><button title="Refresh" onClick={()=>load().catch(()=>{})}><RefreshCcw size={14}/></button><button onClick={()=>setOpen(false)}><X size={18}/></button></div></header><div className="notification-list">{busy&&<div className="empty-state">Refreshing…</div>}{!busy&&items.length===0&&<div className="empty-state">No new notifications.</div>}{!busy&&items.map(item=><article key={item.id}><div className="notification-kind">{item.kind.includes('message')?<Mail size={13}/>:<Bell size={13}/>}<span>{item.kind}</span></div><strong>{item.title}</strong><p>{item.detail}</p><time>{item.date?new Date(item.date).toLocaleString('en-GB',{dateStyle:'short',timeStyle:'short'}):''}</time></article>)}</div><footer><button className="secondary-button" onClick={()=>setOpen(false)}>Close</button></footer></div></ModalPortal>}</>
}
