// RecordsWeb GP medication catalogue.
// Source: user-supplied "GP MEDS.pdf" (8 pages).
// The catalogue intentionally preserves the PDF wording verbatim rather than
// silently altering medicine forms, indications or dose text.

export const GP_MEDICATION_CATALOGUE = [
  {
    "id": "core-001",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 1,
    "medicine": "Atorvastatin",
    "form": "Tablet",
    "indication": "High cholesterol / CVD prevention",
    "usualDose": "20 mg once daily",
    "higherDose": "40–80 mg once daily",
    "nhsArea": ""
  },
  {
    "id": "core-002",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 2,
    "medicine": "Amlodipine",
    "form": "Tablet",
    "indication": "Hypertension / angina",
    "usualDose": "5 mg once daily",
    "higherDose": "10 mg once daily",
    "nhsArea": ""
  },
  {
    "id": "core-003",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 3,
    "medicine": "Ramipril",
    "form": "Tablet/capsule",
    "indication": "Hypertension / HF / CKD",
    "usualDose": "1.25–2.5 mg once daily",
    "higherDose": "5–10 mg once daily",
    "nhsArea": ""
  },
  {
    "id": "core-004",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 4,
    "medicine": "Bisoprolol",
    "form": "Tablet",
    "indication": "HF / AF / hypertension",
    "usualDose": "1.25–5 mg once daily",
    "higherDose": "Up to 10 mg once daily, indication dependent",
    "nhsArea": ""
  },
  {
    "id": "core-005",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 5,
    "medicine": "Losartan",
    "form": "Tablet",
    "indication": "Hypertension / CKD",
    "usualDose": "50 mg once daily",
    "higherDose": "100 mg once daily",
    "nhsArea": ""
  },
  {
    "id": "core-006",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 6,
    "medicine": "Furosemide",
    "form": "Tablet",
    "indication": "Oedema / HF",
    "usualDose": "20–40 mg once daily",
    "higherDose": "Titrate to response",
    "nhsArea": ""
  },
  {
    "id": "core-007",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 7,
    "medicine": "Candesartan",
    "form": "Tablet",
    "indication": "Hypertension / HF",
    "usualDose": "4–8 mg once daily",
    "higherDose": "Up to 32 mg once daily",
    "nhsArea": ""
  },
  {
    "id": "core-008",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 8,
    "medicine": "Valsartan",
    "form": "Tablet",
    "indication": "Hypertension / HF",
    "usualDose": "40–80 mg once/twice daily",
    "higherDose": "Indication dependent",
    "nhsArea": ""
  },
  {
    "id": "core-009",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 9,
    "medicine": "Indapamide",
    "form": "Tablet",
    "indication": "Hypertension",
    "usualDose": "2.5 mg once daily",
    "higherDose": "Usually no escalation",
    "nhsArea": ""
  },
  {
    "id": "core-010",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 10,
    "medicine": "Bendroflumethiazide",
    "form": "Tablet",
    "indication": "Hypertension",
    "usualDose": "2.5 mg once daily",
    "higherDose": "Usually no escalation",
    "nhsArea": ""
  },
  {
    "id": "core-011",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 11,
    "medicine": "Perindopril",
    "form": "Tablet",
    "indication": "Hypertension / CVD",
    "usualDose": "2 mg once daily",
    "higherDose": "Up to 8 mg once daily",
    "nhsArea": ""
  },
  {
    "id": "core-012",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 12,
    "medicine": "Doxazosin",
    "form": "Tablet",
    "indication": "BPH / hypertension",
    "usualDose": "1 mg once daily",
    "higherDose": "Up to 16 mg/day depending on indication",
    "nhsArea": ""
  },
  {
    "id": "core-013",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 13,
    "medicine": "Lisinopril",
    "form": "Tablet",
    "indication": "Hypertension / HF",
    "usualDose": "2.5–10 mg once daily",
    "higherDose": "Up to 40 mg once daily",
    "nhsArea": ""
  },
  {
    "id": "core-014",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 14,
    "medicine": "Nifedipine MR",
    "form": "Modified-release tablet",
    "indication": "Hypertension / angina",
    "usualDose": "30 mg once daily",
    "higherDose": "Up to 90 mg/day depending on product",
    "nhsArea": ""
  },
  {
    "id": "core-015",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 15,
    "medicine": "Diltiazem MR",
    "form": "Modified-release tablet/capsule",
    "indication": "AF / angina / hypertension",
    "usualDose": "120–200 mg/day",
    "higherDose": "Product-specific",
    "nhsArea": ""
  },
  {
    "id": "core-016",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 16,
    "medicine": "Verapamil MR",
    "form": "Modified-release tablet",
    "indication": "AF / angina",
    "usualDose": "120–240 mg/day",
    "higherDose": "Product-specific",
    "nhsArea": ""
  },
  {
    "id": "core-017",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 17,
    "medicine": "Spironolactone",
    "form": "Tablet",
    "indication": "HF / resistant hypertension",
    "usualDose": "25 mg once daily",
    "higherDose": "Often 25–50 mg/day",
    "nhsArea": ""
  },
  {
    "id": "core-018",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 18,
    "medicine": "Eplerenone",
    "form": "Tablet",
    "indication": "Heart failure",
    "usualDose": "25 mg once daily",
    "higherDose": "Up to 50 mg once daily",
    "nhsArea": ""
  },
  {
    "id": "core-019",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 19,
    "medicine": "Isosorbide mononitrate MR",
    "form": "Modified-release tablet",
    "indication": "Angina",
    "usualDose": "25–60 mg once daily",
    "higherDose": "Product-specific",
    "nhsArea": ""
  },
  {
    "id": "core-020",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 20,
    "medicine": "Glyceryl trinitrate",
    "form": "Sublingual spray/tablet",
    "indication": "Acute angina",
    "usualDose": "1 dose at onset",
    "higherDose": "Repeat according to product instructions",
    "nhsArea": ""
  },
  {
    "id": "core-021",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 21,
    "medicine": "Aspirin",
    "form": "Gastro-resistant tablet",
    "indication": "Secondary CVD prevention",
    "usualDose": "75 mg once daily",
    "higherDose": "Usually 75 mg daily",
    "nhsArea": ""
  },
  {
    "id": "core-022",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 22,
    "medicine": "Clopidogrel",
    "form": "Tablet",
    "indication": "Antiplatelet therapy",
    "usualDose": "75 mg once daily",
    "higherDose": "Usually 75 mg daily",
    "nhsArea": ""
  },
  {
    "id": "core-023",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 23,
    "medicine": "Rosuvastatin",
    "form": "Tablet",
    "indication": "High cholesterol",
    "usualDose": "5–10 mg once daily",
    "higherDose": "Up to 40 mg once daily",
    "nhsArea": ""
  },
  {
    "id": "core-024",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 24,
    "medicine": "Simvastatin",
    "form": "Tablet",
    "indication": "High cholesterol",
    "usualDose": "10–20 mg once daily",
    "higherDose": "Up to 40 mg once daily in selected patients",
    "nhsArea": ""
  },
  {
    "id": "core-025",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 25,
    "medicine": "Ezetimibe",
    "form": "Tablet",
    "indication": "High cholesterol",
    "usualDose": "10 mg once daily",
    "higherDose": "Usually no escalation",
    "nhsArea": ""
  },
  {
    "id": "core-026",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 26,
    "medicine": "Fenofibrate",
    "form": "Tablet/capsule",
    "indication": "Hypertriglyceridaemia",
    "usualDose": "Product-specific",
    "higherDose": "Product-specific",
    "nhsArea": ""
  },
  {
    "id": "core-027",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 27,
    "medicine": "Apixaban",
    "form": "Tablet",
    "indication": "AF / VTE",
    "usualDose": "Usually 5 mg twice daily",
    "higherDose": "2.5 mg twice daily when reduction criteria apply",
    "nhsArea": ""
  },
  {
    "id": "core-028",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 28,
    "medicine": "Rivaroxaban",
    "form": "Tablet",
    "indication": "AF / VTE",
    "usualDose": "Indication-specific",
    "higherDose": "Indication-specific",
    "nhsArea": ""
  },
  {
    "id": "core-029",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 29,
    "medicine": "Warfarin",
    "form": "Tablet",
    "indication": "Anticoagulation",
    "usualDose": "Individualised",
    "higherDose": "Adjusted to INR",
    "nhsArea": ""
  },
  {
    "id": "core-030",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 30,
    "medicine": "Edoxaban",
    "form": "Tablet",
    "indication": "AF / VTE",
    "usualDose": "Usually 60 mg once daily",
    "higherDose": "30 mg once daily in specified patients",
    "nhsArea": ""
  },
  {
    "id": "core-031",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 31,
    "medicine": "Metformin",
    "form": "Tablet / MR",
    "indication": "Type 2 diabetes",
    "usualDose": "500 mg once daily",
    "higherDose": "Up to 1 g twice daily commonly",
    "nhsArea": ""
  },
  {
    "id": "core-032",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 32,
    "medicine": "Gliclazide",
    "form": "Tablet / MR",
    "indication": "Type 2 diabetes",
    "usualDose": "40–80 mg daily",
    "higherDose": "Titrate; product-specific maximum",
    "nhsArea": ""
  },
  {
    "id": "core-033",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 33,
    "medicine": "Sitagliptin",
    "form": "Tablet",
    "indication": "Type 2 diabetes",
    "usualDose": "100 mg once daily",
    "higherDose": "Usually no escalation",
    "nhsArea": ""
  },
  {
    "id": "core-034",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 34,
    "medicine": "Empagliflozin",
    "form": "Tablet",
    "indication": "T2DM / HF / CKD",
    "usualDose": "10 mg once daily",
    "higherDose": "25 mg once daily for appropriate diabetes patients",
    "nhsArea": ""
  },
  {
    "id": "core-035",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 35,
    "medicine": "Dapagliflozin",
    "form": "Tablet",
    "indication": "T2DM / HF / CKD",
    "usualDose": "10 mg once daily",
    "higherDose": "Usually no escalation",
    "nhsArea": ""
  },
  {
    "id": "core-036",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 36,
    "medicine": "Pioglitazone",
    "form": "Tablet",
    "indication": "Type 2 diabetes",
    "usualDose": "15–30 mg once daily",
    "higherDose": "Up to 45 mg once daily",
    "nhsArea": ""
  },
  {
    "id": "core-037",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 37,
    "medicine": "Linagliptin",
    "form": "Tablet",
    "indication": "Type 2 diabetes",
    "usualDose": "5 mg once daily",
    "higherDose": "Usually no escalation",
    "nhsArea": ""
  },
  {
    "id": "core-038",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 38,
    "medicine": "Repaglinide",
    "form": "Tablet",
    "indication": "Type 2 diabetes",
    "usualDose": "0.5 mg before meals",
    "higherDose": "Titrate; up to 4 mg before meals",
    "nhsArea": ""
  },
  {
    "id": "core-039",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 39,
    "medicine": "Semaglutide",
    "form": "Injection",
    "indication": "T2DM / weight management",
    "usualDose": "Low-dose weekly initiation",
    "higherDose": "Gradual product-specific escalation",
    "nhsArea": ""
  },
  {
    "id": "core-040",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 40,
    "medicine": "Dulaglutide",
    "form": "Injection",
    "indication": "Type 2 diabetes",
    "usualDose": "0.75 mg once weekly",
    "higherDose": "Gradual product-specific escalation",
    "nhsArea": ""
  },
  {
    "id": "core-041",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 1,
    "sourceNumber": 41,
    "medicine": "Liraglutide",
    "form": "Injection",
    "indication": "T2DM / weight management",
    "usualDose": "0.6 mg once daily",
    "higherDose": "Gradual product-specific escalation",
    "nhsArea": ""
  },
  {
    "id": "core-042",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 42,
    "medicine": "Insulin glargine",
    "form": "Injection",
    "indication": "Diabetes",
    "usualDose": "Individualised",
    "higherDose": "Titrate to glucose readings",
    "nhsArea": ""
  },
  {
    "id": "core-043",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 43,
    "medicine": "Insulin detemir",
    "form": "Injection",
    "indication": "Diabetes",
    "usualDose": "Individualised",
    "higherDose": "Titrate to glucose readings",
    "nhsArea": ""
  },
  {
    "id": "core-044",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 44,
    "medicine": "Insulin aspart",
    "form": "Injection",
    "indication": "Diabetes",
    "usualDose": "Individualised with meals",
    "higherDose": "Titrate to carbohydrate/glucose needs",
    "nhsArea": ""
  },
  {
    "id": "core-045",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 45,
    "medicine": "Insulin lispro",
    "form": "Injection",
    "indication": "Diabetes",
    "usualDose": "Individualised with meals",
    "higherDose": "Titrate to carbohydrate/glucose needs",
    "nhsArea": ""
  },
  {
    "id": "core-046",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 46,
    "medicine": "Levothyroxine",
    "form": "Tablet",
    "indication": "Hypothyroidism",
    "usualDose": "Individualised",
    "higherDose": "Adjust according to TSH",
    "nhsArea": ""
  },
  {
    "id": "core-047",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 47,
    "medicine": "Carbimazole",
    "form": "Tablet",
    "indication": "Hyperthyroidism",
    "usualDose": "15–40 mg/day depending on severity",
    "higherDose": "Titrate using thyroid tests",
    "nhsArea": ""
  },
  {
    "id": "core-048",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 48,
    "medicine": "Alendronic acid",
    "form": "Tablet",
    "indication": "Osteoporosis",
    "usualDose": "70 mg once weekly",
    "higherDose": "Usually no escalation",
    "nhsArea": ""
  },
  {
    "id": "core-049",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 49,
    "medicine": "Risedronate",
    "form": "Tablet",
    "indication": "Osteoporosis",
    "usualDose": "35 mg once weekly",
    "higherDose": "Usually no escalation",
    "nhsArea": ""
  },
  {
    "id": "core-050",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 50,
    "medicine": "Colecalciferol",
    "form": "Capsule/tablet",
    "indication": "Vitamin D deficiency",
    "usualDose": "Severity dependent",
    "higherDose": "Loading then maintenance where indicated",
    "nhsArea": ""
  },
  {
    "id": "core-051",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 51,
    "medicine": "Calcium carbonate",
    "form": "Tablet",
    "indication": "Calcium supplementation",
    "usualDose": "Individualised",
    "higherDose": "Product-specific",
    "nhsArea": ""
  },
  {
    "id": "core-052",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 52,
    "medicine": "Folic acid",
    "form": "Tablet",
    "indication": "Folate deficiency",
    "usualDose": "5 mg once daily",
    "higherDose": "Usually no escalation",
    "nhsArea": ""
  },
  {
    "id": "core-053",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 53,
    "medicine": "Ferrous sulfate",
    "form": "Tablet",
    "indication": "Iron-deficiency anaemia",
    "usualDose": "200 mg once daily commonly",
    "higherDose": "Adjust to tolerance/response",
    "nhsArea": ""
  },
  {
    "id": "core-054",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 54,
    "medicine": "Cyanocobalamin",
    "form": "Injection/tablet",
    "indication": "B12 deficiency",
    "usualDose": "Cause/regimen dependent",
    "higherDose": "Loading then maintenance where indicated",
    "nhsArea": ""
  },
  {
    "id": "core-055",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 55,
    "medicine": "Salbutamol",
    "form": "Inhaler",
    "indication": "Asthma / COPD",
    "usualDose": "1–2 puffs PRN",
    "higherDose": "Product/condition-specific maximum",
    "nhsArea": ""
  },
  {
    "id": "core-056",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 56,
    "medicine": "Beclometasone",
    "form": "Inhaler",
    "indication": "Asthma",
    "usualDose": "Product-specific low dose",
    "higherDose": "Step up/down according to control",
    "nhsArea": ""
  },
  {
    "id": "core-057",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 57,
    "medicine": "Budesonide",
    "form": "Inhaler",
    "indication": "Asthma / COPD",
    "usualDose": "Product-specific",
    "higherDose": "Step up/down according to control",
    "nhsArea": ""
  },
  {
    "id": "core-058",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 58,
    "medicine": "Fluticasone",
    "form": "Inhaler",
    "indication": "Asthma / COPD / rhinitis",
    "usualDose": "Product-specific",
    "higherDose": "Step according to control",
    "nhsArea": ""
  },
  {
    "id": "core-059",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 59,
    "medicine": "Mometasone",
    "form": "Nasal spray/inhaler",
    "indication": "Rhinitis / asthma",
    "usualDose": "Product-specific",
    "higherDose": "Adjust to control",
    "nhsArea": ""
  },
  {
    "id": "core-060",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 60,
    "medicine": "Ciclesonide",
    "form": "Inhaler",
    "indication": "Asthma",
    "usualDose": "Product-specific",
    "higherDose": "Step according to control",
    "nhsArea": ""
  },
  {
    "id": "core-061",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 61,
    "medicine": "Formoterol",
    "form": "Inhaler",
    "indication": "Asthma / COPD",
    "usualDose": "Product-specific",
    "higherDose": "Usually combination therapy",
    "nhsArea": ""
  },
  {
    "id": "core-062",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 62,
    "medicine": "Salmeterol",
    "form": "Inhaler",
    "indication": "Asthma / COPD",
    "usualDose": "50 micrograms twice daily commonly",
    "higherDose": "Product-specific",
    "nhsArea": ""
  },
  {
    "id": "core-063",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 63,
    "medicine": "Tiotropium",
    "form": "Inhaler",
    "indication": "COPD / selected asthma",
    "usualDose": "Product-specific once daily",
    "higherDose": "Usually fixed",
    "nhsArea": ""
  },
  {
    "id": "core-064",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 64,
    "medicine": "Glycopyrronium",
    "form": "Inhaler",
    "indication": "COPD",
    "usualDose": "Product-specific once daily",
    "higherDose": "Usually fixed",
    "nhsArea": ""
  },
  {
    "id": "core-065",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 65,
    "medicine": "Ipratropium",
    "form": "Inhaler/nebuliser",
    "indication": "COPD / bronchospasm",
    "usualDose": "Product-specific",
    "higherDose": "Frequency depends on severity",
    "nhsArea": ""
  },
  {
    "id": "core-066",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 66,
    "medicine": "Montelukast",
    "form": "Tablet",
    "indication": "Asthma / allergic rhinitis",
    "usualDose": "10 mg nightly",
    "higherDose": "Usually no escalation",
    "nhsArea": ""
  },
  {
    "id": "core-067",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 67,
    "medicine": "Fostair",
    "form": "Inhaler",
    "indication": "Asthma / COPD",
    "usualDose": "Product-specific",
    "higherDose": "Step according to control",
    "nhsArea": ""
  },
  {
    "id": "core-068",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 68,
    "medicine": "Symbicort",
    "form": "Inhaler",
    "indication": "Asthma / COPD",
    "usualDose": "Product-specific",
    "higherDose": "Step according to control",
    "nhsArea": ""
  },
  {
    "id": "core-069",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 69,
    "medicine": "Seretide",
    "form": "Inhaler",
    "indication": "Asthma / COPD",
    "usualDose": "Product-specific",
    "higherDose": "Step according to control",
    "nhsArea": ""
  },
  {
    "id": "core-070",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 70,
    "medicine": "Relvar Ellipta",
    "form": "Inhaler",
    "indication": "Asthma / COPD",
    "usualDose": "1 inhalation once daily",
    "higherDose": "Product-specific",
    "nhsArea": ""
  },
  {
    "id": "core-071",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 71,
    "medicine": "Trelegy Ellipta",
    "form": "Inhaler",
    "indication": "COPD",
    "usualDose": "1 inhalation once daily",
    "higherDose": "Usually fixed",
    "nhsArea": ""
  },
  {
    "id": "core-072",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 72,
    "medicine": "Prednisolone",
    "form": "Tablet",
    "indication": "Respiratory exacerbations / inflammation",
    "usualDose": "Often 30–40 mg once daily for acute respiratory exacerbation",
    "higherDose": "Short course; indication-specific",
    "nhsArea": ""
  },
  {
    "id": "core-073",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 73,
    "medicine": "Cetirizine",
    "form": "Tablet",
    "indication": "Allergy",
    "usualDose": "10 mg once daily",
    "higherDose": "Usually no escalation",
    "nhsArea": ""
  },
  {
    "id": "core-074",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 74,
    "medicine": "Loratadine",
    "form": "Tablet",
    "indication": "Allergy",
    "usualDose": "10 mg once daily",
    "higherDose": "Usually no escalation",
    "nhsArea": ""
  },
  {
    "id": "core-075",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 75,
    "medicine": "Fexofenadine",
    "form": "Tablet",
    "indication": "Allergy",
    "usualDose": "120–180 mg once daily depending on indication",
    "higherDose": "Product-specific",
    "nhsArea": ""
  },
  {
    "id": "core-076",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 76,
    "medicine": "Chlorphenamine",
    "form": "Tablet",
    "indication": "Allergy",
    "usualDose": "4 mg up to four times daily",
    "higherDose": "Up to 24 mg/day; sedation limits use",
    "nhsArea": ""
  },
  {
    "id": "core-077",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 77,
    "medicine": "Sodium cromoglicate",
    "form": "Eye drops/inhaler",
    "indication": "Allergy",
    "usualDose": "Product-specific",
    "higherDose": "Product-specific",
    "nhsArea": ""
  },
  {
    "id": "core-078",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 78,
    "medicine": "Fluticasone nasal spray",
    "form": "Nasal spray",
    "indication": "Allergic rhinitis",
    "usualDose": "1–2 sprays each nostril once daily",
    "higherDose": "Reduce when controlled",
    "nhsArea": ""
  },
  {
    "id": "core-079",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 79,
    "medicine": "Lansoprazole",
    "form": "Capsule",
    "indication": "GORD / dyspepsia",
    "usualDose": "15–30 mg once daily",
    "higherDose": "30 mg once/twice daily for selected indications",
    "nhsArea": ""
  },
  {
    "id": "core-080",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 80,
    "medicine": "Omeprazole",
    "form": "Capsule/tablet",
    "indication": "GORD / dyspepsia",
    "usualDose": "20 mg once daily",
    "higherDose": "40 mg/day or indication-specific higher dose",
    "nhsArea": ""
  },
  {
    "id": "core-081",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 81,
    "medicine": "Esomeprazole",
    "form": "Capsule/tablet",
    "indication": "GORD",
    "usualDose": "20 mg once daily",
    "higherDose": "40 mg once daily commonly",
    "nhsArea": ""
  },
  {
    "id": "core-082",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 82,
    "medicine": "Pantoprazole",
    "form": "Tablet",
    "indication": "GORD",
    "usualDose": "20–40 mg once daily",
    "higherDose": "40 mg once/twice daily depending on indication",
    "nhsArea": ""
  },
  {
    "id": "core-083",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 83,
    "medicine": "Famotidine",
    "form": "Tablet",
    "indication": "Dyspepsia / reflux",
    "usualDose": "20 mg once/twice daily",
    "higherDose": "Product/renal dependent",
    "nhsArea": ""
  },
  {
    "id": "core-084",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 84,
    "medicine": "Gaviscon",
    "form": "Liquid/tablet",
    "indication": "Reflux",
    "usualDose": "After meals and at bedtime",
    "higherDose": "Adjust to symptoms",
    "nhsArea": ""
  },
  {
    "id": "core-085",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 85,
    "medicine": "Mebeverine",
    "form": "Tablet/capsule",
    "indication": "IBS",
    "usualDose": "135 mg three times daily or MR equivalent",
    "higherDose": "Usually no escalation",
    "nhsArea": ""
  },
  {
    "id": "core-086",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 86,
    "medicine": "Hyoscine butylbromide",
    "form": "Tablet",
    "indication": "Abdominal cramps / IBS",
    "usualDose": "10–20 mg up to four times daily",
    "higherDose": "Up to 20 mg four times daily",
    "nhsArea": ""
  },
  {
    "id": "core-087",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 87,
    "medicine": "Loperamide",
    "form": "Capsule/tablet",
    "indication": "Diarrhoea",
    "usualDose": "4 mg initially, then 2 mg after loose stool",
    "higherDose": "Product/indication maximum",
    "nhsArea": ""
  },
  {
    "id": "core-088",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 2,
    "sourceNumber": 88,
    "medicine": "Macrogol",
    "form": "Sachets",
    "indication": "Constipation",
    "usualDose": "1 sachet 1–3 times daily",
    "higherDose": "Higher regimens for faecal loading",
    "nhsArea": ""
  },
  {
    "id": "core-089",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 89,
    "medicine": "Lactulose",
    "form": "Oral solution",
    "indication": "Constipation",
    "usualDose": "15 mL twice daily",
    "higherDose": "Adjust to response",
    "nhsArea": ""
  },
  {
    "id": "core-090",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 90,
    "medicine": "Senna",
    "form": "Tablet",
    "indication": "Constipation",
    "usualDose": "7.5–15 mg at night",
    "higherDose": "Adjust to response",
    "nhsArea": ""
  },
  {
    "id": "core-091",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 91,
    "medicine": "Bisacodyl",
    "form": "Tablet/suppository",
    "indication": "Constipation",
    "usualDose": "5–10 mg at night",
    "higherDose": "Usually up to 10 mg daily",
    "nhsArea": ""
  },
  {
    "id": "core-092",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 92,
    "medicine": "Docusate",
    "form": "Capsule/liquid",
    "indication": "Constipation",
    "usualDose": "100 mg twice daily",
    "higherDose": "Product-specific maximum",
    "nhsArea": ""
  },
  {
    "id": "core-093",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 93,
    "medicine": "Mesalazine",
    "form": "Tablet/granules",
    "indication": "IBD",
    "usualDose": "Formulation/disease dependent",
    "higherDose": "Step according to activity",
    "nhsArea": ""
  },
  {
    "id": "core-094",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 94,
    "medicine": "Ondansetron",
    "form": "Tablet/ODT",
    "indication": "Nausea/vomiting",
    "usualDose": "4–8 mg depending on indication",
    "higherDose": "Product-specific",
    "nhsArea": ""
  },
  {
    "id": "core-095",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 95,
    "medicine": "Metoclopramide",
    "form": "Tablet",
    "indication": "Nausea/vomiting",
    "usualDose": "10 mg up to three times daily",
    "higherDose": "Maximum 30 mg/day; usually max 5 days",
    "nhsArea": ""
  },
  {
    "id": "core-096",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 96,
    "medicine": "Domperidone",
    "form": "Tablet",
    "indication": "Nausea/vomiting",
    "usualDose": "10 mg up to three times daily",
    "higherDose": "Maximum 30 mg/day; short-term",
    "nhsArea": ""
  },
  {
    "id": "core-097",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 97,
    "medicine": "Amoxicillin",
    "form": "Capsule/suspension",
    "indication": "Bacterial infection",
    "usualDose": "250–500 mg three times daily commonly",
    "higherDose": "Indication-specific higher doses",
    "nhsArea": ""
  },
  {
    "id": "core-098",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 98,
    "medicine": "Phenoxymethylpenicillin",
    "form": "Tablet",
    "indication": "Bacterial infection",
    "usualDose": "500 mg four times daily commonly",
    "higherDose": "Guideline/indication-specific",
    "nhsArea": ""
  },
  {
    "id": "core-099",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 99,
    "medicine": "Flucloxacillin",
    "form": "Capsule",
    "indication": "Bacterial infection",
    "usualDose": "500 mg four times daily commonly",
    "higherDose": "Higher doses in selected severe infections",
    "nhsArea": ""
  },
  {
    "id": "core-100",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 100,
    "medicine": "Co-amoxiclav",
    "form": "Tablet",
    "indication": "Bacterial infection",
    "usualDose": "500/125 mg three times daily commonly",
    "higherDose": "Indication-specific",
    "nhsArea": ""
  },
  {
    "id": "core-101",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 101,
    "medicine": "Doxycycline",
    "form": "Capsule/tablet",
    "indication": "Bacterial infection / acne",
    "usualDose": "100–200 mg initially depending on indication",
    "higherDose": "Usually lower maintenance",
    "nhsArea": ""
  },
  {
    "id": "core-102",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 102,
    "medicine": "Clarithromycin",
    "form": "Tablet",
    "indication": "Bacterial infection",
    "usualDose": "250–500 mg twice daily",
    "higherDose": "Indication-specific",
    "nhsArea": ""
  },
  {
    "id": "core-103",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 103,
    "medicine": "Azithromycin",
    "form": "Tablet",
    "indication": "Bacterial infection",
    "usualDose": "500 mg once daily for selected infections",
    "higherDose": "Indication-specific",
    "nhsArea": ""
  },
  {
    "id": "core-104",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 104,
    "medicine": "Cefalexin",
    "form": "Capsule",
    "indication": "Bacterial infection",
    "usualDose": "500 mg 2–3 times daily commonly",
    "higherDose": "Higher doses in selected severe infections",
    "nhsArea": ""
  },
  {
    "id": "core-105",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 105,
    "medicine": "Nitrofurantoin MR",
    "form": "Capsule/tablet",
    "indication": "UTI",
    "usualDose": "100 mg twice daily commonly",
    "higherDose": "Usually short course",
    "nhsArea": ""
  },
  {
    "id": "core-106",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 106,
    "medicine": "Trimethoprim",
    "form": "Tablet",
    "indication": "UTI",
    "usualDose": "200 mg twice daily commonly",
    "higherDose": "Usually short course",
    "nhsArea": ""
  },
  {
    "id": "core-107",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 107,
    "medicine": "Metronidazole",
    "form": "Tablet/gel",
    "indication": "Bacterial/anaerobic infection",
    "usualDose": "400 mg 2–3 times daily depending on indication",
    "higherDose": "Indication-specific",
    "nhsArea": ""
  },
  {
    "id": "core-108",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 108,
    "medicine": "Fluconazole",
    "form": "Capsule",
    "indication": "Fungal infection",
    "usualDose": "150 mg single dose for selected candidiasis",
    "higherDose": "Other infections require different regimens",
    "nhsArea": ""
  },
  {
    "id": "core-109",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 109,
    "medicine": "Clotrimazole",
    "form": "Cream/pessary",
    "indication": "Fungal infection",
    "usualDose": "Product-specific",
    "higherDose": "Product-specific",
    "nhsArea": ""
  },
  {
    "id": "core-110",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 110,
    "medicine": "Terbinafine",
    "form": "Tablet/cream",
    "indication": "Fungal infection",
    "usualDose": "250 mg once daily orally for selected infections",
    "higherDose": "Course depends on site",
    "nhsArea": ""
  },
  {
    "id": "core-111",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 111,
    "medicine": "Aciclovir",
    "form": "Tablet/cream",
    "indication": "Herpes infection",
    "usualDose": "Indication-specific",
    "higherDose": "Indication-specific",
    "nhsArea": ""
  },
  {
    "id": "core-112",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 112,
    "medicine": "Valaciclovir",
    "form": "Tablet",
    "indication": "Herpes infection",
    "usualDose": "Indication-specific",
    "higherDose": "Indication-specific",
    "nhsArea": ""
  },
  {
    "id": "core-113",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 113,
    "medicine": "Fusidic acid",
    "form": "Cream/ointment",
    "indication": "Bacterial skin infection",
    "usualDose": "Apply 2–3 times daily",
    "higherDose": "Short course",
    "nhsArea": ""
  },
  {
    "id": "core-114",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 114,
    "medicine": "Mupirocin",
    "form": "Ointment",
    "indication": "Bacterial skin infection",
    "usualDose": "Apply 2–3 times daily",
    "higherDose": "Short course",
    "nhsArea": ""
  },
  {
    "id": "core-115",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 115,
    "medicine": "Hydrocortisone",
    "form": "Cream/ointment",
    "indication": "Eczema / dermatitis",
    "usualDose": "Apply once or twice daily",
    "higherDose": "Short course; potency/site dependent",
    "nhsArea": ""
  },
  {
    "id": "core-116",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 116,
    "medicine": "Clobetasone",
    "form": "Cream/ointment",
    "indication": "Eczema / dermatitis",
    "usualDose": "Apply once or twice daily",
    "higherDose": "Short course; step down",
    "nhsArea": ""
  },
  {
    "id": "core-117",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 117,
    "medicine": "Betamethasone",
    "form": "Cream/ointment",
    "indication": "Inflammatory skin disease",
    "usualDose": "Apply once/twice daily",
    "higherDose": "Potency/duration depend on site",
    "nhsArea": ""
  },
  {
    "id": "core-118",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 118,
    "medicine": "Clobetasol",
    "form": "Cream/ointment",
    "indication": "Severe inflammatory skin disease",
    "usualDose": "Apply once/twice daily",
    "higherDose": "Usually short-term only",
    "nhsArea": ""
  },
  {
    "id": "core-119",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 119,
    "medicine": "Adapalene",
    "form": "Gel/cream",
    "indication": "Acne",
    "usualDose": "Apply once nightly",
    "higherDose": "Increase as tolerated",
    "nhsArea": ""
  },
  {
    "id": "core-120",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 120,
    "medicine": "Benzoyl peroxide",
    "form": "Gel/wash",
    "indication": "Acne",
    "usualDose": "Apply once daily",
    "higherDose": "May increase to twice daily if tolerated",
    "nhsArea": ""
  },
  {
    "id": "core-121",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 121,
    "medicine": "Tretinoin",
    "form": "Cream/gel",
    "indication": "Acne",
    "usualDose": "Apply once nightly",
    "higherDose": "Gradual introduction",
    "nhsArea": ""
  },
  {
    "id": "core-122",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 122,
    "medicine": "Isotretinoin",
    "form": "Capsule",
    "indication": "Severe acne",
    "usualDose": "Specialist initiated; weight-based",
    "higherDose": "Specialist titration",
    "nhsArea": ""
  },
  {
    "id": "core-123",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 123,
    "medicine": "Calcipotriol",
    "form": "Ointment/cream",
    "indication": "Psoriasis",
    "usualDose": "Apply once/twice daily",
    "higherDose": "Product-specific maximum",
    "nhsArea": ""
  },
  {
    "id": "core-124",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 124,
    "medicine": "Ketoconazole",
    "form": "Cream/shampoo",
    "indication": "Fungal infection / seborrhoeic dermatitis",
    "usualDose": "Product-specific",
    "higherDose": "Product-specific",
    "nhsArea": ""
  },
  {
    "id": "core-125",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 125,
    "medicine": "Tamsulosin",
    "form": "Capsule/tablet",
    "indication": "BPH",
    "usualDose": "400 micrograms once daily",
    "higherDose": "Usually no escalation",
    "nhsArea": ""
  },
  {
    "id": "core-126",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 126,
    "medicine": "Finasteride",
    "form": "Tablet",
    "indication": "BPH",
    "usualDose": "5 mg once daily",
    "higherDose": "Usually fixed",
    "nhsArea": ""
  },
  {
    "id": "core-127",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 127,
    "medicine": "Dutasteride",
    "form": "Capsule",
    "indication": "BPH",
    "usualDose": "500 micrograms once daily",
    "higherDose": "Usually fixed",
    "nhsArea": ""
  },
  {
    "id": "core-128",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 128,
    "medicine": "Oxybutynin",
    "form": "Tablet/MR",
    "indication": "Overactive bladder",
    "usualDose": "2.5–5 mg 2–3 times daily depending on formulation",
    "higherDose": "Product-specific",
    "nhsArea": ""
  },
  {
    "id": "core-129",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 129,
    "medicine": "Mirabegron",
    "form": "MR tablet",
    "indication": "Overactive bladder",
    "usualDose": "50 mg once daily",
    "higherDose": "25 mg in selected patients",
    "nhsArea": ""
  },
  {
    "id": "core-130",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 130,
    "medicine": "Solifenacin",
    "form": "Tablet",
    "indication": "Overactive bladder",
    "usualDose": "5 mg once daily",
    "higherDose": "10 mg once daily",
    "nhsArea": ""
  },
  {
    "id": "core-131",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 131,
    "medicine": "Tolterodine",
    "form": "Tablet/MR",
    "indication": "Overactive bladder",
    "usualDose": "2 mg twice daily or MR 4 mg daily",
    "higherDose": "Product-specific",
    "nhsArea": ""
  },
  {
    "id": "core-132",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 132,
    "medicine": "Sildenafil",
    "form": "Tablet",
    "indication": "Erectile dysfunction",
    "usualDose": "50 mg as required",
    "higherDose": "25–100 mg according to response",
    "nhsArea": ""
  },
  {
    "id": "core-133",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 133,
    "medicine": "Tadalafil",
    "form": "Tablet",
    "indication": "Erectile dysfunction / BPH",
    "usualDose": "10 mg as required or 2.5–5 mg daily",
    "higherDose": "20 mg as required maximum",
    "nhsArea": ""
  },
  {
    "id": "core-134",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 3,
    "sourceNumber": 134,
    "medicine": "Vardenafil",
    "form": "Tablet",
    "indication": "Erectile dysfunction",
    "usualDose": "10 mg as required",
    "higherDose": "Up to 20 mg as appropriate",
    "nhsArea": ""
  },
  {
    "id": "core-135",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 135,
    "medicine": "Vaginal oestrogen",
    "form": "Vaginal preparation",
    "indication": "Genitourinary menopause symptoms",
    "usualDose": "Product-specific loading regimen",
    "higherDose": "Maintenance product-specific",
    "nhsArea": ""
  },
  {
    "id": "core-136",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 136,
    "medicine": "HRT oestrogen",
    "form": "Patch/gel/tablet",
    "indication": "Menopausal symptoms",
    "usualDose": "Product-specific",
    "higherDose": "Lowest effective dose",
    "nhsArea": ""
  },
  {
    "id": "core-137",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 137,
    "medicine": "Micronised progesterone",
    "form": "Capsule",
    "indication": "HRT endometrial protection",
    "usualDose": "100–200 mg according to regimen",
    "higherDose": "Product-specific",
    "nhsArea": ""
  },
  {
    "id": "core-138",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 138,
    "medicine": "Norethisterone",
    "form": "Tablet",
    "indication": "Heavy menstrual bleeding / other indications",
    "usualDose": "5 mg 2–3 times daily depending on indication",
    "higherDose": "Indication-specific",
    "nhsArea": ""
  },
  {
    "id": "core-139",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 139,
    "medicine": "Medroxyprogesterone",
    "form": "Tablet/injection",
    "indication": "Gynaecological indications",
    "usualDose": "Indication-specific",
    "higherDose": "Indication-specific",
    "nhsArea": ""
  },
  {
    "id": "core-140",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 140,
    "medicine": "Paracetamol",
    "form": "Tablet/capsule",
    "indication": "Pain / fever",
    "usualDose": "500 mg–1 g up to four times daily",
    "higherDose": "Maximum 4 g/day in suitable adults",
    "nhsArea": ""
  },
  {
    "id": "core-141",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 141,
    "medicine": "Ibuprofen",
    "form": "Tablet/capsule",
    "indication": "Pain / inflammation",
    "usualDose": "200–400 mg up to three times daily",
    "higherDose": "Up to 2.4 g/day in selected prescribed use",
    "nhsArea": ""
  },
  {
    "id": "core-142",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 142,
    "medicine": "Naproxen",
    "form": "Tablet",
    "indication": "Pain / inflammation",
    "usualDose": "250–500 mg once/twice daily",
    "higherDose": "Indication-specific",
    "nhsArea": ""
  },
  {
    "id": "core-143",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 143,
    "medicine": "Diclofenac",
    "form": "Tablet",
    "indication": "Pain / inflammation",
    "usualDose": "50 mg 2–3 times daily",
    "higherDose": "Usually maximum 150 mg/day",
    "nhsArea": ""
  },
  {
    "id": "core-144",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 144,
    "medicine": "Celecoxib",
    "form": "Capsule",
    "indication": "Pain / arthritis",
    "usualDose": "100 mg once/twice daily",
    "higherDose": "Up to 200 mg twice daily depending on indication",
    "nhsArea": ""
  },
  {
    "id": "core-145",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 145,
    "medicine": "Etoricoxib",
    "form": "Tablet",
    "indication": "Arthritis / acute pain",
    "usualDose": "30–60 mg once daily",
    "higherDose": "Up to 120 mg/day for selected indications",
    "nhsArea": ""
  },
  {
    "id": "core-146",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 146,
    "medicine": "Co-codamol",
    "form": "Tablet/capsule",
    "indication": "Pain",
    "usualDose": "8/500 or 15/500 mg, 1–2 tablets up to four times daily",
    "higherDose": "Higher strengths only when appropriate; total paracetamol limit",
    "nhsArea": ""
  },
  {
    "id": "core-147",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 147,
    "medicine": "Codeine",
    "form": "Tablet",
    "indication": "Pain",
    "usualDose": "15–30 mg up to four times daily",
    "higherDose": "Up to 60 mg four times daily in selected adults",
    "nhsArea": ""
  },
  {
    "id": "core-148",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 148,
    "medicine": "Tramadol",
    "form": "Capsule/tablet",
    "indication": "Pain",
    "usualDose": "50–100 mg up to four times daily",
    "higherDose": "Usually max 400 mg/day",
    "nhsArea": ""
  },
  {
    "id": "core-149",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 149,
    "medicine": "Dihydrocodeine",
    "form": "Tablet",
    "indication": "Pain",
    "usualDose": "30 mg up to four times daily",
    "higherDose": "Up to 240 mg/day commonly",
    "nhsArea": ""
  },
  {
    "id": "core-150",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 150,
    "medicine": "Morphine",
    "form": "Tablet/oral solution",
    "indication": "Severe pain",
    "usualDose": "Individualised",
    "higherDose": "Titrate carefully",
    "nhsArea": ""
  },
  {
    "id": "core-151",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 151,
    "medicine": "Buprenorphine patch",
    "form": "Transdermal",
    "indication": "Chronic pain",
    "usualDose": "Low-strength patch initially",
    "higherDose": "Titrate by patch strength",
    "nhsArea": ""
  },
  {
    "id": "core-152",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 152,
    "medicine": "Fentanyl patch",
    "form": "Transdermal",
    "indication": "Severe chronic pain",
    "usualDose": "Specialist/experienced prescriber",
    "higherDose": "Titrate by patch strength",
    "nhsArea": ""
  },
  {
    "id": "core-153",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 153,
    "medicine": "Capsaicin",
    "form": "Cream",
    "indication": "Neuropathic pain",
    "usualDose": "Apply according to product",
    "higherDose": "Adjust to response",
    "nhsArea": ""
  },
  {
    "id": "core-154",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 154,
    "medicine": "Lidocaine",
    "form": "Plaster",
    "indication": "Localised neuropathic pain",
    "usualDose": "Up to 3 plasters/day depending on product",
    "higherDose": "Product-specific",
    "nhsArea": ""
  },
  {
    "id": "core-155",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 155,
    "medicine": "Diclofenac gel",
    "form": "Topical gel",
    "indication": "Musculoskeletal pain",
    "usualDose": "Apply 2–4 times daily",
    "higherDose": "Product-specific",
    "nhsArea": ""
  },
  {
    "id": "core-156",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 156,
    "medicine": "Ibuprofen gel",
    "form": "Topical gel",
    "indication": "Musculoskeletal pain",
    "usualDose": "Apply 3–4 times daily",
    "higherDose": "Product-specific",
    "nhsArea": ""
  },
  {
    "id": "core-157",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 157,
    "medicine": "Ketoprofen gel",
    "form": "Topical gel",
    "indication": "Musculoskeletal pain",
    "usualDose": "Apply 2–4 times daily",
    "higherDose": "Product-specific",
    "nhsArea": ""
  },
  {
    "id": "core-158",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 158,
    "medicine": "Baclofen",
    "form": "Tablet",
    "indication": "Muscle spasm",
    "usualDose": "5 mg three times daily",
    "higherDose": "Gradual titration; specialist-level higher doses",
    "nhsArea": ""
  },
  {
    "id": "core-159",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 159,
    "medicine": "Allopurinol",
    "form": "Tablet",
    "indication": "Gout prevention",
    "usualDose": "100 mg once daily",
    "higherDose": "Increase gradually to urate target",
    "nhsArea": ""
  },
  {
    "id": "core-160",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 160,
    "medicine": "Colchicine",
    "form": "Tablet",
    "indication": "Acute gout / prophylaxis",
    "usualDose": "500 micrograms 2–4 times daily depending on indication",
    "higherDose": "Dose-limited; toxicity risk",
    "nhsArea": ""
  },
  {
    "id": "core-161",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 161,
    "medicine": "Duloxetine",
    "form": "Capsule",
    "indication": "Depression / neuropathic pain",
    "usualDose": "60 mg once daily commonly",
    "higherDose": "Up to 120 mg/day for selected indications",
    "nhsArea": ""
  },
  {
    "id": "core-162",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 162,
    "medicine": "Venlafaxine",
    "form": "Tablet/capsule",
    "indication": "Depression / anxiety",
    "usualDose": "75 mg/day commonly",
    "higherDose": "Higher doses require careful monitoring",
    "nhsArea": ""
  },
  {
    "id": "core-163",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 163,
    "medicine": "Escitalopram",
    "form": "Tablet",
    "indication": "Depression / anxiety",
    "usualDose": "10 mg once daily",
    "higherDose": "20 mg once daily; lower maximum in some patients",
    "nhsArea": ""
  },
  {
    "id": "core-164",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 164,
    "medicine": "Fluoxetine",
    "form": "Capsule",
    "indication": "Depression",
    "usualDose": "20 mg once daily",
    "higherDose": "Up to 60 mg/day depending on indication",
    "nhsArea": ""
  },
  {
    "id": "core-165",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 165,
    "medicine": "Mirtazapine",
    "form": "Tablet",
    "indication": "Depression",
    "usualDose": "15 mg at night",
    "higherDose": "30–45 mg nightly",
    "nhsArea": ""
  },
  {
    "id": "core-166",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 166,
    "medicine": "Amitriptyline",
    "form": "Tablet",
    "indication": "Neuropathic pain",
    "usualDose": "10 mg at night",
    "higherDose": "Often 25–75 mg/day for pain",
    "nhsArea": ""
  },
  {
    "id": "core-167",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 167,
    "medicine": "Nortriptyline",
    "form": "Tablet",
    "indication": "Neuropathic pain",
    "usualDose": "10 mg at night",
    "higherDose": "Often 25–75 mg/day",
    "nhsArea": ""
  },
  {
    "id": "core-168",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 168,
    "medicine": "Pregabalin",
    "form": "Capsule/oral solution",
    "indication": "Neuropathic pain",
    "usualDose": "25–75 mg once/twice daily",
    "higherDose": "Up to 600 mg/day in selected indications",
    "nhsArea": ""
  },
  {
    "id": "core-169",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 169,
    "medicine": "Gabapentin",
    "form": "Capsule/tablet",
    "indication": "Neuropathic pain",
    "usualDose": "300 mg once daily initially",
    "higherDose": "Up to 3.6 g/day in selected adults",
    "nhsArea": ""
  },
  {
    "id": "core-170",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 170,
    "medicine": "Propranolol",
    "form": "Tablet",
    "indication": "Migraine / tremor / anxiety",
    "usualDose": "10–40 mg depending on indication",
    "higherDose": "Indication-specific",
    "nhsArea": ""
  },
  {
    "id": "core-171",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 171,
    "medicine": "Zopiclone",
    "form": "Tablet",
    "indication": "Short-term insomnia",
    "usualDose": "3.75–7.5 mg at night",
    "higherDose": "7.5 mg nightly maximum commonly",
    "nhsArea": ""
  },
  {
    "id": "core-172",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 172,
    "medicine": "Melatonin MR",
    "form": "Modified-release tablet",
    "indication": "Insomnia",
    "usualDose": "2 mg 1–2 hours before bedtime",
    "higherDose": "Product/indication-specific",
    "nhsArea": ""
  },
  {
    "id": "core-173",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 173,
    "medicine": "Diazepam",
    "form": "Tablet",
    "indication": "Anxiety / muscle spasm",
    "usualDose": "2–5 mg 2–3 times daily depending on indication",
    "higherDose": "Short-term, cautious use",
    "nhsArea": ""
  },
  {
    "id": "core-174",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 174,
    "medicine": "Lorazepam",
    "form": "Tablet",
    "indication": "Severe anxiety / short-term use",
    "usualDose": "0.5–1 mg depending on indication",
    "higherDose": "Short-term only",
    "nhsArea": ""
  },
  {
    "id": "core-175",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 175,
    "medicine": "Carbamazepine",
    "form": "Tablet",
    "indication": "Epilepsy / neuropathic pain",
    "usualDose": "Indication-specific",
    "higherDose": "Gradual titration",
    "nhsArea": ""
  },
  {
    "id": "core-176",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 176,
    "medicine": "Sodium valproate",
    "form": "Tablet",
    "indication": "Epilepsy / bipolar disorder",
    "usualDose": "Individualised",
    "higherDose": "Gradual titration",
    "nhsArea": ""
  },
  {
    "id": "core-177",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 4,
    "sourceNumber": 177,
    "medicine": "Lamotrigine",
    "form": "Tablet",
    "indication": "Epilepsy / bipolar disorder",
    "usualDose": "Very low initial dose",
    "higherDose": "Slow titration",
    "nhsArea": ""
  },
  {
    "id": "core-178",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 5,
    "sourceNumber": 178,
    "medicine": "Levetiracetam",
    "form": "Tablet",
    "indication": "Epilepsy",
    "usualDose": "500 mg twice daily commonly",
    "higherDose": "Up to 1.5 g twice daily in selected adults",
    "nhsArea": ""
  },
  {
    "id": "core-179",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 5,
    "sourceNumber": 179,
    "medicine": "Topiramate",
    "form": "Tablet",
    "indication": "Migraine prevention / epilepsy",
    "usualDose": "25 mg at night initially",
    "higherDose": "Gradual titration",
    "nhsArea": ""
  },
  {
    "id": "core-180",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 5,
    "sourceNumber": 180,
    "medicine": "Sumatriptan",
    "form": "Tablet/nasal/injection",
    "indication": "Migraine",
    "usualDose": "50 mg orally at onset commonly",
    "higherDose": "May increase to 100 mg; formulation dependent",
    "nhsArea": ""
  },
  {
    "id": "core-181",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 5,
    "sourceNumber": 181,
    "medicine": "Rizatriptan",
    "form": "Tablet",
    "indication": "Migraine",
    "usualDose": "10 mg at onset",
    "higherDose": "Repeat/daily maximum product-specific",
    "nhsArea": ""
  },
  {
    "id": "core-182",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 5,
    "sourceNumber": 182,
    "medicine": "Prochlorperazine",
    "form": "Tablet/buccal",
    "indication": "Nausea / vertigo",
    "usualDose": "5–10 mg depending on indication",
    "higherDose": "Product-specific",
    "nhsArea": ""
  },
  {
    "id": "core-183",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 5,
    "sourceNumber": 183,
    "medicine": "Methotrexate",
    "form": "Tablet/injection",
    "indication": "Inflammatory disease",
    "usualDose": "Specialist initiated; low-dose weekly",
    "higherDose": "Specialist titration",
    "nhsArea": ""
  },
  {
    "id": "core-184",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 5,
    "sourceNumber": 184,
    "medicine": "Sulfasalazine",
    "form": "Tablet",
    "indication": "IBD / inflammatory arthritis",
    "usualDose": "500 mg once/twice daily initially",
    "higherDose": "Gradual escalation",
    "nhsArea": ""
  },
  {
    "id": "core-185",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 5,
    "sourceNumber": 185,
    "medicine": "Leflunomide",
    "form": "Tablet",
    "indication": "Rheumatoid arthritis",
    "usualDose": "10–20 mg once daily",
    "higherDose": "Usually 20 mg once daily",
    "nhsArea": ""
  },
  {
    "id": "core-186",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 5,
    "sourceNumber": 186,
    "medicine": "Hydroxychloroquine",
    "form": "Tablet",
    "indication": "Inflammatory arthritis",
    "usualDose": "Weight-based",
    "higherDose": "Specialist adjustment",
    "nhsArea": ""
  },
  {
    "id": "core-187",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 5,
    "sourceNumber": 187,
    "medicine": "Chloramphenicol",
    "form": "Eye drops/ointment",
    "indication": "Bacterial conjunctivitis",
    "usualDose": "Product-specific",
    "higherDose": "Short course",
    "nhsArea": ""
  },
  {
    "id": "core-188",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 5,
    "sourceNumber": 188,
    "medicine": "Sodium chloride nasal spray",
    "form": "Nasal spray",
    "indication": "Nasal congestion/dryness",
    "usualDose": "As required",
    "higherDose": "As required",
    "nhsArea": ""
  },
  {
    "id": "core-189",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 5,
    "sourceNumber": 189,
    "medicine": "Urea cream",
    "form": "Cream",
    "indication": "Dry skin / hyperkeratosis",
    "usualDose": "Apply 1–2 times daily",
    "higherDose": "Increase frequency if needed",
    "nhsArea": ""
  },
  {
    "id": "core-190",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 5,
    "sourceNumber": 190,
    "medicine": "Calcipotriol/betamethasone",
    "form": "Ointment/gel",
    "indication": "Psoriasis",
    "usualDose": "Product-specific once daily",
    "higherDose": "Product-specific maximum",
    "nhsArea": ""
  },
  {
    "id": "core-191",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 5,
    "sourceNumber": 191,
    "medicine": "Eumovate",
    "form": "Cream/ointment",
    "indication": "Eczema / dermatitis",
    "usualDose": "Apply once/twice daily",
    "higherDose": "Short course then step down",
    "nhsArea": ""
  },
  {
    "id": "core-192",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 5,
    "sourceNumber": 192,
    "medicine": "Betnovate",
    "form": "Cream/ointment",
    "indication": "Inflammatory skin disease",
    "usualDose": "Apply once/twice daily",
    "higherDose": "Short course/site dependent",
    "nhsArea": ""
  },
  {
    "id": "core-193",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 5,
    "sourceNumber": 193,
    "medicine": "Dermovate",
    "form": "Cream/ointment",
    "indication": "Severe inflammatory skin disease",
    "usualDose": "Apply once/twice daily",
    "higherDose": "Short-term only",
    "nhsArea": ""
  },
  {
    "id": "core-194",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 5,
    "sourceNumber": 194,
    "medicine": "Fucidin",
    "form": "Cream/ointment",
    "indication": "Bacterial skin infection",
    "usualDose": "Apply 2–3 times daily",
    "higherDose": "Short course",
    "nhsArea": ""
  },
  {
    "id": "core-195",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 5,
    "sourceNumber": 195,
    "medicine": "Adcal",
    "form": "Tablet",
    "indication": "Calcium/vitamin D supplementation",
    "usualDose": "Product-specific",
    "higherDose": "Product-specific",
    "nhsArea": ""
  },
  {
    "id": "core-196",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 5,
    "sourceNumber": 196,
    "medicine": "Cholecalciferol 1,000 IU",
    "form": "Capsule/tablet",
    "indication": "Vitamin D maintenance",
    "usualDose": "1,000 IU once daily commonly",
    "higherDose": "Up to 4,000 IU/day only when clinically appropriate",
    "nhsArea": ""
  },
  {
    "id": "core-197",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 5,
    "sourceNumber": 197,
    "medicine": "Omeprazole 10 mg",
    "form": "Capsule",
    "indication": "Reflux/dyspepsia",
    "usualDose": "10 mg once daily",
    "higherDose": "Increase according to indication",
    "nhsArea": ""
  },
  {
    "id": "core-198",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 5,
    "sourceNumber": 198,
    "medicine": "Gaviscon Advance",
    "form": "Liquid",
    "indication": "Reflux",
    "usualDose": "After meals and bedtime",
    "higherDose": "Adjust to symptoms",
    "nhsArea": ""
  },
  {
    "id": "core-199",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 5,
    "sourceNumber": 199,
    "medicine": "Movicol",
    "form": "Sachet",
    "indication": "Constipation",
    "usualDose": "1 sachet 1–3 times daily",
    "higherDose": "Higher regimen for faecal loading",
    "nhsArea": ""
  },
  {
    "id": "core-200",
    "sourceSection": "NHS GP — 200 Common Medicines Prescribing Reference",
    "sourcePage": 5,
    "sourceNumber": 200,
    "medicine": "Senna syrup",
    "form": "Oral solution",
    "indication": "Constipation",
    "usualDose": "Product-specific",
    "higherDose": "Adjust to response",
    "nhsArea": ""
  },
  {
    "id": "expanded-001",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 6,
    "sourceNumber": null,
    "medicine": "Atenolol",
    "form": "Tablet",
    "indication": "Hypertension / angina / AF rate control",
    "usualDose": "25–50 mg once daily",
    "higherDose": "Usually 50–100 mg once daily",
    "nhsArea": "Cardiovascular"
  },
  {
    "id": "expanded-002",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 6,
    "sourceNumber": null,
    "medicine": "Nebivolol",
    "form": "Tablet",
    "indication": "Hypertension / heart failure",
    "usualDose": "5 mg once daily",
    "higherDose": "Up to 10 mg once daily; HF titration differs",
    "nhsArea": "Cardiovascular"
  },
  {
    "id": "expanded-003",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 6,
    "sourceNumber": null,
    "medicine": "Lercanidipine",
    "form": "Tablet",
    "indication": "Hypertension",
    "usualDose": "10 mg once daily",
    "higherDose": "20 mg once daily",
    "nhsArea": "Cardiovascular"
  },
  {
    "id": "expanded-004",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 6,
    "sourceNumber": null,
    "medicine": "Bumetanide",
    "form": "Tablet",
    "indication": "Oedema / heart failure",
    "usualDose": "0.5–1 mg once daily",
    "higherDose": "Titrate to response",
    "nhsArea": "Cardiovascular"
  },
  {
    "id": "expanded-005",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 6,
    "sourceNumber": null,
    "medicine": "Nicorandil",
    "form": "Tablet",
    "indication": "Angina",
    "usualDose": "10 mg twice daily",
    "higherDose": "20 mg twice daily",
    "nhsArea": "Cardiovascular"
  },
  {
    "id": "expanded-006",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 6,
    "sourceNumber": null,
    "medicine": "Ivabradine",
    "form": "Tablet",
    "indication": "Heart failure / chronic stable angina",
    "usualDose": "5 mg twice daily",
    "higherDose": "Up to 7.5 mg twice daily, specialist/indication dependent",
    "nhsArea": "Cardiovascular"
  },
  {
    "id": "expanded-007",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 6,
    "sourceNumber": null,
    "medicine": "Digoxin",
    "form": "Tablet",
    "indication": "AF / heart failure",
    "usualDose": "Individualised",
    "higherDose": "Dose and monitoring depend on indication, renal function and age",
    "nhsArea": "Cardiovascular / monitoring"
  },
  {
    "id": "expanded-008",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 6,
    "sourceNumber": null,
    "medicine": "Colesevelam",
    "form": "Tablet",
    "indication": "Hypercholesterolaemia",
    "usualDose": "Product-specific",
    "higherDose": "Product-specific",
    "nhsArea": "Lipid management"
  },
  {
    "id": "expanded-009",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 6,
    "sourceNumber": null,
    "medicine": "Alogliptin",
    "form": "Tablet",
    "indication": "Type 2 diabetes",
    "usualDose": "25 mg once daily",
    "higherDose": "Renal impairment requires dose adjustment",
    "nhsArea": "Diabetes"
  },
  {
    "id": "expanded-010",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 6,
    "sourceNumber": null,
    "medicine": "Glimepiride",
    "form": "Tablet",
    "indication": "Type 2 diabetes",
    "usualDose": "1 mg once daily",
    "higherDose": "Titrate according to response; product-specific maximum",
    "nhsArea": "Diabetes"
  },
  {
    "id": "expanded-011",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 6,
    "sourceNumber": null,
    "medicine": "Linagliptin",
    "form": "Tablet",
    "indication": "Type 2 diabetes",
    "usualDose": "5 mg once daily",
    "higherDose": "Usually 5 mg once daily",
    "nhsArea": "Diabetes"
  },
  {
    "id": "expanded-012",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 6,
    "sourceNumber": null,
    "medicine": "Insulin isophane (NPH)",
    "form": "Injection",
    "indication": "Diabetes",
    "usualDose": "Individualised",
    "higherDose": "Titrate to glucose targets",
    "nhsArea": "Diabetes / specialist monitoring"
  },
  {
    "id": "expanded-013",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 6,
    "sourceNumber": null,
    "medicine": "Insulin degludec",
    "form": "Injection",
    "indication": "Diabetes",
    "usualDose": "Individualised",
    "higherDose": "Titrate to glucose targets",
    "nhsArea": "Diabetes / specialist monitoring"
  },
  {
    "id": "expanded-014",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 6,
    "sourceNumber": null,
    "medicine": "Insulin lispro",
    "form": "Injection",
    "indication": "Diabetes",
    "usualDose": "Individualised",
    "higherDose": "Meal-time dose titration",
    "nhsArea": "Diabetes / specialist monitoring"
  },
  {
    "id": "expanded-015",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 6,
    "sourceNumber": null,
    "medicine": "Insulin glulisine",
    "form": "Injection",
    "indication": "Diabetes",
    "usualDose": "Individualised",
    "higherDose": "Meal-time dose titration",
    "nhsArea": "Diabetes / specialist monitoring"
  },
  {
    "id": "expanded-016",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 6,
    "sourceNumber": null,
    "medicine": "Aclidinium",
    "form": "Inhaler",
    "indication": "COPD maintenance",
    "usualDose": "400 micrograms twice daily",
    "higherDose": "Usually 400 micrograms twice daily",
    "nhsArea": "Respiratory"
  },
  {
    "id": "expanded-017",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 6,
    "sourceNumber": null,
    "medicine": "Umeclidinium",
    "form": "Inhaler",
    "indication": "COPD maintenance",
    "usualDose": "62.5 micrograms once daily",
    "higherDose": "Usually 62.5 micrograms once daily",
    "nhsArea": "Respiratory"
  },
  {
    "id": "expanded-018",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 6,
    "sourceNumber": null,
    "medicine": "Indacaterol",
    "form": "Inhaler",
    "indication": "COPD maintenance",
    "usualDose": "Product-specific",
    "higherDose": "Product-specific",
    "nhsArea": "Respiratory"
  },
  {
    "id": "expanded-019",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 6,
    "sourceNumber": null,
    "medicine": "Olodaterol",
    "form": "Inhaler",
    "indication": "COPD maintenance",
    "usualDose": "5 micrograms once daily",
    "higherDose": "Usually 5 micrograms once daily",
    "nhsArea": "Respiratory"
  },
  {
    "id": "expanded-020",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 6,
    "sourceNumber": null,
    "medicine": "Beclometasone/formoter ol",
    "form": "Inhaler",
    "indication": "Asthma / COPD in selected patients",
    "usualDose": "Product-specific",
    "higherDose": "Product-specific; inhaler strength dependent",
    "nhsArea": "Respiratory"
  },
  {
    "id": "expanded-021",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 6,
    "sourceNumber": null,
    "medicine": "Budesonide/formoterol",
    "form": "Inhaler",
    "indication": "Asthma / COPD",
    "usualDose": "Product-specific",
    "higherDose": "Product-specific; MART regimen where appropriate",
    "nhsArea": "Respiratory"
  },
  {
    "id": "expanded-022",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 6,
    "sourceNumber": null,
    "medicine": "Ipratropium bromide",
    "form": "Nebules / inhaler",
    "indication": "Bronchospasm / COPD",
    "usualDose": "Product-specific",
    "higherDose": "Product-specific",
    "nhsArea": "Respiratory"
  },
  {
    "id": "expanded-023",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Salbutamol",
    "form": "Nebules",
    "indication": "Acute bronchospasm",
    "usualDose": "2.5–5 mg by nebuliser",
    "higherDose": "Repeat according to clinical response and local protocol",
    "nhsArea": "Respiratory / urgent care"
  },
  {
    "id": "expanded-024",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Sodium chloride 0.9%",
    "form": "Nebules",
    "indication": "Nebulised therapy / secretion management",
    "usualDose": "Product-specific",
    "higherDose": "Product-specific",
    "nhsArea": "Respiratory"
  },
  {
    "id": "expanded-025",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Famotidine",
    "form": "Tablet",
    "indication": "Dyspepsia / reflux",
    "usualDose": "20 mg once or twice daily",
    "higherDose": "Up to 40 mg twice daily depending on indication",
    "nhsArea": "Gastrointestinal"
  },
  {
    "id": "expanded-026",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Peppermint oil",
    "form": "Capsule",
    "indication": "IBS / abdominal spasm",
    "usualDose": "Product-specific",
    "higherDose": "Product-specific",
    "nhsArea": "Gastrointestinal"
  },
  {
    "id": "expanded-027",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Loperamide",
    "form": "Capsule / tablet",
    "indication": "Acute or chronic diarrhoea",
    "usualDose": "4 mg initially",
    "higherDose": "2 mg after each loose stool; maximum depends on indication/product",
    "nhsArea": "Gastrointestinal"
  },
  {
    "id": "expanded-028",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Docusate sodium",
    "form": "Capsule / oral solution",
    "indication": "Constipation",
    "usualDose": "100 mg twice daily",
    "higherDose": "Up to 500 mg/day depending on formulation",
    "nhsArea": "Gastrointestinal"
  },
  {
    "id": "expanded-029",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Glycerol suppositories",
    "form": "Suppository",
    "indication": "Constipation",
    "usualDose": "1 suppository when required",
    "higherDose": "Product-specific",
    "nhsArea": "Gastrointestinal"
  },
  {
    "id": "expanded-030",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Phosphate enema",
    "form": "Enema",
    "indication": "Constipation / faecal loading",
    "usualDose": "1 enema when required",
    "higherDose": "Avoid repeated use without clinical review",
    "nhsArea": "Gastrointestinal / caution"
  },
  {
    "id": "expanded-031",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Meloxicam",
    "form": "Tablet",
    "indication": "Musculoskeletal pain / inflammation",
    "usualDose": "7.5 mg once daily",
    "higherDose": "Up to 15 mg once daily",
    "nhsArea": "Pain / NSAID"
  },
  {
    "id": "expanded-032",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Piroxicam",
    "form": "Capsule / tablet",
    "indication": "Musculoskeletal pain",
    "usualDose": "Product-specific",
    "higherDose": "Specialist/limited use; lowest effective dose",
    "nhsArea": "Pain / NSAID"
  },
  {
    "id": "expanded-033",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Buprenorphine",
    "form": "Patch / formulation",
    "indication": "Chronic pain",
    "usualDose": "Product-specific",
    "higherDose": "Titrate according to product and indication",
    "nhsArea": "Pain / controlled drug"
  },
  {
    "id": "expanded-034",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Tapentadol",
    "form": "Tablet",
    "indication": "Severe chronic pain",
    "usualDose": "Product-specific",
    "higherDose": "Specialist/controlled-drug prescribing",
    "nhsArea": "Pain / controlled drug"
  },
  {
    "id": "expanded-035",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Morphine oral solution",
    "form": "Oral solution",
    "indication": "Severe pain",
    "usualDose": "Individualised",
    "higherDose": "Titrate to response; controlled-drug prescribing",
    "nhsArea": "Pain / controlled drug"
  },
  {
    "id": "expanded-036",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Paroxetine",
    "form": "Tablet",
    "indication": "Depression / anxiety disorders",
    "usualDose": "20 mg once daily",
    "higherDose": "Up to 50 mg/day depending on indication",
    "nhsArea": "Mental health"
  },
  {
    "id": "expanded-037",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Vortioxetine",
    "form": "Tablet",
    "indication": "Depression",
    "usualDose": "10 mg once daily",
    "higherDose": "5–20 mg once daily",
    "nhsArea": "Mental health"
  },
  {
    "id": "expanded-038",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Aripiprazole",
    "form": "Tablet",
    "indication": "Psychiatric disorders",
    "usualDose": "Specialist initiated",
    "higherDose": "Dose depends on indication",
    "nhsArea": "Mental health / specialist"
  },
  {
    "id": "expanded-039",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Quetiapine",
    "form": "Tablet / MR",
    "indication": "Psychiatric disorders",
    "usualDose": "Specialist initiated",
    "higherDose": "Dose depends on indication",
    "nhsArea": "Mental health / specialist"
  },
  {
    "id": "expanded-040",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Olanzapine",
    "form": "Tablet / orodispersible",
    "indication": "Psychiatric disorders",
    "usualDose": "Specialist initiated",
    "higherDose": "Dose depends on indication",
    "nhsArea": "Mental health / specialist"
  },
  {
    "id": "expanded-041",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Risperidone",
    "form": "Tablet / oral solution",
    "indication": "Psychiatric disorders",
    "usualDose": "Specialist initiated",
    "higherDose": "Dose depends on indication",
    "nhsArea": "Mental health / specialist"
  },
  {
    "id": "expanded-042",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Lithium",
    "form": "Tablet",
    "indication": "Bipolar disorder",
    "usualDose": "Specialist initiated",
    "higherDose": "Individualised to serum level",
    "nhsArea": "Mental health / high monitoring"
  },
  {
    "id": "expanded-043",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Methylphenidate",
    "form": "Tablet / MR",
    "indication": "ADHD",
    "usualDose": "Specialist initiated",
    "higherDose": "Titrate according to response and formulation",
    "nhsArea": "ADHD / controlled drug"
  },
  {
    "id": "expanded-044",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Lisdexamfetamine",
    "form": "Capsule",
    "indication": "ADHD",
    "usualDose": "Specialist initiated",
    "higherDose": "Titrate according to response",
    "nhsArea": "ADHD / controlled drug"
  },
  {
    "id": "expanded-045",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Sodium valproate",
    "form": "Tablet / liquid",
    "indication": "Epilepsy / bipolar disorder",
    "usualDose": "Specialist initiated",
    "higherDose": "Indication-specific; major safety restrictions apply",
    "nhsArea": "Neurology / high-risk"
  },
  {
    "id": "expanded-046",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Carbamazepine",
    "form": "Tablet / liquid",
    "indication": "Epilepsy / trigeminal neuralgia",
    "usualDose": "100–200 mg once or twice daily",
    "higherDose": "Titrate according to indication and levels where required",
    "nhsArea": "Neurology / monitoring"
  },
  {
    "id": "expanded-047",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Lamotrigine",
    "form": "Tablet / dispersible",
    "indication": "Epilepsy / bipolar disorder",
    "usualDose": "Low-dose titration required",
    "higherDose": "Slow titration; indication-specific",
    "nhsArea": "Neurology / monitoring"
  },
  {
    "id": "expanded-048",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Levetiracetam",
    "form": "Tablet / oral solution",
    "indication": "Epilepsy",
    "usualDose": "500 mg twice daily",
    "higherDose": "Up to 1.5 g twice daily depending on indication",
    "nhsArea": "Neurology"
  },
  {
    "id": "expanded-049",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Topiramate",
    "form": "Tablet / sprinkle capsule",
    "indication": "Epilepsy / migraine prevention",
    "usualDose": "Low-dose titration",
    "higherDose": "Indication-specific maximum",
    "nhsArea": "Neurology"
  },
  {
    "id": "expanded-050",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Amitriptyline",
    "form": "Tablet / liquid",
    "indication": "Neuropathic pain / migraine prevention",
    "usualDose": "10 mg at night",
    "higherDose": "Titrate gradually; pain doses usually lower than antidepressant doses",
    "nhsArea": "Neurology / pain"
  },
  {
    "id": "expanded-051",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 7,
    "sourceNumber": null,
    "medicine": "Gabapentin",
    "form": "Capsule / tablet",
    "indication": "Neuropathic pain / epilepsy",
    "usualDose": "300 mg once daily initially",
    "higherDose": "Titrate gradually; renal adjustment required",
    "nhsArea": "Neurology / monitoring"
  },
  {
    "id": "expanded-052",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 8,
    "sourceNumber": null,
    "medicine": "Pregabalin",
    "form": "Capsule / oral solution",
    "indication": "Neuropathic pain / epilepsy",
    "usualDose": "75 mg twice daily",
    "higherDose": "Up to 300 mg twice daily depending on indication; renal adjustment",
    "nhsArea": "Neurology / controlled drug"
  },
  {
    "id": "expanded-053",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 8,
    "sourceNumber": null,
    "medicine": "Alfuzosin",
    "form": "Modified-release tablet",
    "indication": "BPH",
    "usualDose": "10 mg once daily",
    "higherDose": "Usually 10 mg once daily",
    "nhsArea": "Urology"
  },
  {
    "id": "expanded-054",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 8,
    "sourceNumber": null,
    "medicine": "Solifenacin",
    "form": "Tablet",
    "indication": "Overactive bladder",
    "usualDose": "5 mg once daily",
    "higherDose": "10 mg once daily if tolerated",
    "nhsArea": "Urology"
  },
  {
    "id": "expanded-055",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 8,
    "sourceNumber": null,
    "medicine": "Tolterodine",
    "form": "Modified-release capsule / tablet",
    "indication": "Overactive bladder",
    "usualDose": "2 mg/day MR commonly",
    "higherDose": "Dose depends on formulation and tolerability",
    "nhsArea": "Urology"
  },
  {
    "id": "expanded-056",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 8,
    "sourceNumber": null,
    "medicine": "Mirabegron",
    "form": "Modified-release tablet",
    "indication": "Overactive bladder",
    "usualDose": "50 mg once daily",
    "higherDose": "25 mg once daily in selected patients",
    "nhsArea": "Urology"
  },
  {
    "id": "expanded-057",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 8,
    "sourceNumber": null,
    "medicine": "Vibegron",
    "form": "Tablet",
    "indication": "Overactive bladder",
    "usualDose": "75 mg once daily",
    "higherDose": "Usually 75 mg once daily",
    "nhsArea": "Urology"
  },
  {
    "id": "expanded-058",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 8,
    "sourceNumber": null,
    "medicine": "Desogestrel",
    "form": "Tablet",
    "indication": "Progestogen-only contraception",
    "usualDose": "1 tablet once daily",
    "higherDose": "One tablet daily",
    "nhsArea": "Women's health"
  },
  {
    "id": "expanded-059",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 8,
    "sourceNumber": null,
    "medicine": "Tranexamic acid",
    "form": "Tablet",
    "indication": "Heavy menstrual bleeding",
    "usualDose": "1 g three times daily",
    "higherDose": "Up to 4 g/day depending on indication",
    "nhsArea": "Women's health"
  },
  {
    "id": "expanded-060",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 8,
    "sourceNumber": null,
    "medicine": "Estradiol",
    "form": "Patch / gel",
    "indication": "Menopausal hormone therapy",
    "usualDose": "Product-specific",
    "higherDose": "Titrate to symptom control",
    "nhsArea": "Women's health"
  },
  {
    "id": "expanded-061",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 8,
    "sourceNumber": null,
    "medicine": "Tacrolimus",
    "form": "Ointment",
    "indication": "Atopic dermatitis",
    "usualDose": "Apply thinly once or twice daily depending on strength",
    "higherDose": "Use according to severity and specialist/BNF guidance",
    "nhsArea": "Dermatology"
  },
  {
    "id": "expanded-062",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 8,
    "sourceNumber": null,
    "medicine": "Pimecrolimus",
    "form": "Cream",
    "indication": "Atopic dermatitis",
    "usualDose": "Apply twice daily",
    "higherDose": "Use according to clinical response",
    "nhsArea": "Dermatology"
  },
  {
    "id": "expanded-063",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 8,
    "sourceNumber": null,
    "medicine": "Epaderm",
    "form": "Cream / ointment",
    "indication": "Emollient therapy",
    "usualDose": "Apply as required",
    "higherDose": "Use liberally and regularly",
    "nhsArea": "Dermatology"
  },
  {
    "id": "expanded-064",
    "sourceSection": "NHS GP — Expanded NHS England Additions",
    "sourcePage": 8,
    "sourceNumber": null,
    "medicine": "Doublebase",
    "form": "Gel",
    "indication": "Emollient therapy",
    "usualDose": "Apply as required",
    "higherDose": "Use liberally and regularly",
    "nhsArea": "Dermatology"
  }
]

function normalise(value) {
  return String(value || '').trim().toLowerCase()
}

export function searchGpMedicationCatalogue(query, limit = 14) {
  const needle = normalise(query)
  if (!needle) return []

  return GP_MEDICATION_CATALOGUE
    .map((entry, index) => {
      const medicine = normalise(entry.medicine)
      const form = normalise(entry.form)
      const indication = normalise(entry.indication)
      const area = normalise(entry.nhsArea)
      let score = 99
      if (medicine === needle) score = 0
      else if (medicine.startsWith(needle)) score = 1
      else if (medicine.includes(needle)) score = 2
      else if (form.includes(needle)) score = 3
      else if (indication.includes(needle)) score = 4
      else if (area.includes(needle)) score = 5
      return { entry, index, score }
    })
    .filter((item) => item.score < 99)
    .sort((a, b) => a.score - b.score || a.entry.medicine.localeCompare(b.entry.medicine) || a.index - b.index)
    .slice(0, Math.max(1, Number(limit) || 14))
    .map((item) => item.entry)
}

export function medicationCatalogueEntryById(id) {
  return GP_MEDICATION_CATALOGUE.find((entry) => entry.id === id) || null
}

export const GP_MEDICATION_CATALOGUE_SOURCE_NOTE =
  'Dose text is reproduced from the supplied GP MEDS.pdf. The PDF states that doses are general adult reference examples only and must be checked against current BNF, NICE/CKS, SPC/product information, renal/hepatic function, interactions, age, pregnancy status, monitoring requirements and the applicable local formulary.'

export function isSpecialistMedication(entry) {
  if (!entry) return false
  return /\bspecialist\b/i.test([
    entry.usualDose,
    entry.higherDose,
    entry.nhsArea,
  ].filter(Boolean).join(' '))
}
