import React, { useEffect, useState } from 'react'
import { Car, ChevronRight, Plus, Search } from 'lucide-react'
import { Link } from 'react-router-dom'
import { createPoliceVehicle, listPolicePersons, listPoliceVehicles } from '../lib/policingService'

const EMPTY = { registration:'', make:'', model:'', colour:'', status:'active', owner_person_id:'', notes:'' }
export default function PolicingVehiclesPage() {
  const [search,setSearch]=useState(''); const [rows,setRows]=useState([]); const [persons,setPersons]=useState([]); const [form,setForm]=useState(EMPTY); const [showForm,setShowForm]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
  async function load(){setError('');try{const[v,p]=await Promise.all([listPoliceVehicles(search),listPolicePersons('')]);setRows(v);setPersons(p)}catch(e){setError(e?.message||'Unable to load vehicles.')}}
  useEffect(()=>{void load()},[])
  async function submit(e){e.preventDefault();setBusy(true);setError('');try{await createPoliceVehicle({...form,registration:form.registration.toUpperCase(),owner_person_id:form.owner_person_id||null});setForm(EMPTY);setShowForm(false);await load()}catch(err){setError(err?.message||'Unable to create vehicle.')}finally{setBusy(false)}}
  return <div className="policing-page page-pad compact-pad"><div className="policing-page-head"><div><span>POLICING · VEHICLES</span><h1>Vehicle search</h1></div><button className="primary-button" onClick={()=>setShowForm(v=>!v)}><Plus size={15}/>New vehicle</button></div><div className="policing-search"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Registration, make, model or reference"/><button onClick={load}>Search</button></div>{error&&<div className="form-error">{error}</div>}{showForm&&<form className="policing-form" onSubmit={submit}><h3>Create vehicle record</h3><div className="policing-form-grid"><label><span>Registration</span><input required value={form.registration} onChange={e=>setForm({...form,registration:e.target.value})}/></label><label><span>Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>active</option><option>stolen</option><option>seized</option><option>wanted</option><option>inactive</option></select></label><label><span>Make</span><input value={form.make} onChange={e=>setForm({...form,make:e.target.value})}/></label><label><span>Model</span><input value={form.model} onChange={e=>setForm({...form,model:e.target.value})}/></label><label><span>Colour</span><input value={form.colour} onChange={e=>setForm({...form,colour:e.target.value})}/></label><label><span>Linked owner</span><select value={form.owner_person_id} onChange={e=>setForm({...form,owner_person_id:e.target.value})}><option value="">Not linked</option>{persons.map(p=><option key={p.id} value={p.id}>{p.last_name}, {p.first_name} · {p.reference}</option>)}</select></label><label className="wide"><span>Notes</span><textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><div className="policing-form-actions"><button type="button" onClick={()=>setShowForm(false)}>Cancel</button><button className="primary-button" disabled={busy}>{busy?'Saving…':'Create vehicle'}</button></div></form>}<div className="policing-list">{rows.length===0?<div className="empty-state">No vehicle records found.</div>:rows.map(row=><article key={row.id}><Car size={19}/><div><div className="police-list-title-row"><Link to={`/policing/vehicles/${row.id}`}><strong>{row.registration}</strong></Link><Link className="police-open-link" to={`/policing/vehicles/${row.id}`}>Open record <ChevronRight size={12}/></Link></div><span>{row.reference} · {[row.make,row.model,row.colour].filter(Boolean).join(' · ')||'Vehicle details incomplete'}</span><p>Status: {row.status||'active'}{row.owner?` · Owner: ${row.owner.last_name}, ${row.owner.first_name}`:''}</p></div></article>)}</div></div>
}
